// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TENCOMMON_TEN_SERIALIZATION_COMMON_H_
#define FLATBUFFERS_GENERATED_TENCOMMON_TEN_SERIALIZATION_COMMON_H_

#include "flatbuffers/flatbuffers.h"

namespace TEN {
namespace Serialization {
namespace Common {

struct Short;
struct ShortBuilder;
struct ShortT;

struct Int;
struct IntBuilder;
struct IntT;

struct Float;
struct FloatBuilder;
struct FloatT;

struct EulerAngles;

struct Vector2;

struct Vector3;

struct Vector4;

struct GameVector;

struct Pose;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) EulerAngles FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x_;
  int16_t y_;
  int16_t z_;

 public:
  struct Traits;
  EulerAngles()
      : x_(0),
        y_(0),
        z_(0) {
  }
  EulerAngles(int16_t _x, int16_t _y, int16_t _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  int16_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int16_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  int16_t z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(EulerAngles, 6);

struct EulerAngles::Traits {
  using type = EulerAngles;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  struct Traits;
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

struct Vector2::Traits {
  using type = Vector2;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

struct Vector3::Traits {
  using type = Vector3;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  struct Traits;
  Vector4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vector4(float _x, float _y, float _z, float _w)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vector4, 16);

struct Vector4::Traits {
  using type = Vector4;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) GameVector FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;
  int32_t z_;
  int32_t room_number_;

 public:
  struct Traits;
  GameVector()
      : x_(0),
        y_(0),
        z_(0),
        room_number_(0) {
  }
  GameVector(int32_t _x, int32_t _y, int32_t _z, int32_t _room_number)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        room_number_(flatbuffers::EndianScalar(_room_number)) {
  }
  int32_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  int32_t z() const {
    return flatbuffers::EndianScalar(z_);
  }
  int32_t room_number() const {
    return flatbuffers::EndianScalar(room_number_);
  }
};
FLATBUFFERS_STRUCT_END(GameVector, 16);

struct GameVector::Traits {
  using type = GameVector;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Pose FLATBUFFERS_FINAL_CLASS {
 private:
  TEN::Serialization::Common::Vector3 position_;
  TEN::Serialization::Common::EulerAngles orientation_;
  int16_t padding0__;
  TEN::Serialization::Common::Vector3 scale_;

 public:
  struct Traits;
  Pose()
      : position_(),
        orientation_(),
        padding0__(0),
        scale_() {
    (void)padding0__;
  }
  Pose(const TEN::Serialization::Common::Vector3 &_position, const TEN::Serialization::Common::EulerAngles &_orientation, const TEN::Serialization::Common::Vector3 &_scale)
      : position_(_position),
        orientation_(_orientation),
        padding0__(0),
        scale_(_scale) {
    (void)padding0__;
  }
  const TEN::Serialization::Common::Vector3 &position() const {
    return position_;
  }
  const TEN::Serialization::Common::EulerAngles &orientation() const {
    return orientation_;
  }
  const TEN::Serialization::Common::Vector3 &scale() const {
    return scale_;
  }
};
FLATBUFFERS_STRUCT_END(Pose, 32);

struct Pose::Traits {
  using type = Pose;
};

struct ShortT : public flatbuffers::NativeTable {
  typedef Short TableType;
  int16_t scalar = 0;
};

struct Short FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ShortT NativeTableType;
  typedef ShortBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  int16_t scalar() const {
    return GetField<int16_t>(VT_SCALAR, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
  ShortT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ShortT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Short> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ShortT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ShortBuilder {
  typedef Short Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(int16_t scalar) {
    fbb_.AddElement<int16_t>(Short::VT_SCALAR, scalar, 0);
  }
  explicit ShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Short> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Short>(end);
    return o;
  }
};

inline flatbuffers::Offset<Short> CreateShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t scalar = 0) {
  ShortBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct Short::Traits {
  using type = Short;
  static auto constexpr Create = CreateShort;
};

flatbuffers::Offset<Short> CreateShort(flatbuffers::FlatBufferBuilder &_fbb, const ShortT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct IntT : public flatbuffers::NativeTable {
  typedef Int TableType;
  int32_t scalar = 0;
};

struct Int FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef IntT NativeTableType;
  typedef IntBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  int32_t scalar() const {
    return GetField<int32_t>(VT_SCALAR, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
  IntT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(IntT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Int> Pack(flatbuffers::FlatBufferBuilder &_fbb, const IntT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct IntBuilder {
  typedef Int Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(int32_t scalar) {
    fbb_.AddElement<int32_t>(Int::VT_SCALAR, scalar, 0);
  }
  explicit IntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Int> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Int>(end);
    return o;
  }
};

inline flatbuffers::Offset<Int> CreateInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t scalar = 0) {
  IntBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct Int::Traits {
  using type = Int;
  static auto constexpr Create = CreateInt;
};

flatbuffers::Offset<Int> CreateInt(flatbuffers::FlatBufferBuilder &_fbb, const IntT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct FloatT : public flatbuffers::NativeTable {
  typedef Float TableType;
  double scalar = 0.0;
};

struct Float FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FloatT NativeTableType;
  typedef FloatBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  double scalar() const {
    return GetField<double>(VT_SCALAR, 0.0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
  FloatT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(FloatT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Float> Pack(flatbuffers::FlatBufferBuilder &_fbb, const FloatT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct FloatBuilder {
  typedef Float Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(double scalar) {
    fbb_.AddElement<double>(Float::VT_SCALAR, scalar, 0.0);
  }
  explicit FloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Float> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Float>(end);
    return o;
  }
};

inline flatbuffers::Offset<Float> CreateFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    double scalar = 0.0) {
  FloatBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct Float::Traits {
  using type = Float;
  static auto constexpr Create = CreateFloat;
};

flatbuffers::Offset<Float> CreateFloat(flatbuffers::FlatBufferBuilder &_fbb, const FloatT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ShortT *Short::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<ShortT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Short::UnPackTo(ShortT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = scalar(); _o->scalar = _e; }
}

inline flatbuffers::Offset<Short> Short::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ShortT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateShort(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Short> CreateShort(flatbuffers::FlatBufferBuilder &_fbb, const ShortT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ShortT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _scalar = _o->scalar;
  return TEN::Serialization::Common::CreateShort(
      _fbb,
      _scalar);
}

inline IntT *Int::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<IntT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Int::UnPackTo(IntT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = scalar(); _o->scalar = _e; }
}

inline flatbuffers::Offset<Int> Int::Pack(flatbuffers::FlatBufferBuilder &_fbb, const IntT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInt(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Int> CreateInt(flatbuffers::FlatBufferBuilder &_fbb, const IntT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const IntT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _scalar = _o->scalar;
  return TEN::Serialization::Common::CreateInt(
      _fbb,
      _scalar);
}

inline FloatT *Float::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<FloatT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Float::UnPackTo(FloatT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = scalar(); _o->scalar = _e; }
}

inline flatbuffers::Offset<Float> Float::Pack(flatbuffers::FlatBufferBuilder &_fbb, const FloatT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateFloat(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Float> CreateFloat(flatbuffers::FlatBufferBuilder &_fbb, const FloatT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const FloatT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _scalar = _o->scalar;
  return TEN::Serialization::Common::CreateFloat(
      _fbb,
      _scalar);
}

}  // namespace Common
}  // namespace Serialization
}  // namespace TEN

#endif  // FLATBUFFERS_GENERATED_TENCOMMON_TEN_SERIALIZATION_COMMON_H_
