#pragma once

// This file is generated automatically, do not edit it.
// Last generated on 05/08/2025.

#include <unordered_map>
#include <string>
#include "Objects/game_object_ids.h"

/// Constants for object IDs.
// @enum Objects.ObjID
// @pragma nostrip

static const std::unordered_map<std::string, GAME_OBJECT_ID> GAME_OBJECT_IDS {
	/// Object ID.
	// @mem LARA
	{ "LARA", ID_LARA },
	/// Object ID.
	// @mem LARA_EXTRA_ANIMS
	{ "LARA_EXTRA_ANIMS", ID_LARA_EXTRA_ANIMS },
	/// Object ID.
	// @mem PISTOLS_ANIM
	{ "PISTOLS_ANIM", ID_PISTOLS_ANIM },
	/// Object ID.
	// @mem UZI_ANIM
	{ "UZI_ANIM", ID_UZI_ANIM },
	/// Object ID.
	// @mem SHOTGUN_ANIM
	{ "SHOTGUN_ANIM", ID_SHOTGUN_ANIM },
	/// Object ID.
	// @mem REVOLVER_ANIM
	{ "REVOLVER_ANIM", ID_REVOLVER_ANIM },
	/// Object ID.
	// @mem CROSSBOW_ANIM
	{ "CROSSBOW_ANIM", ID_CROSSBOW_ANIM },
	/// Object ID.
	// @mem HK_ANIM
	{ "HK_ANIM", ID_HK_ANIM },
	/// Object ID.
	// @mem GRENADE_ANIM
	{ "GRENADE_ANIM", ID_GRENADE_ANIM },
	/// Object ID.
	// @mem ROCKET_ANIM
	{ "ROCKET_ANIM", ID_ROCKET_ANIM },
	/// Object ID.
	// @mem HARPOON_ANIM
	{ "HARPOON_ANIM", ID_HARPOON_ANIM },
	/// Object ID.
	// @mem FLARE_ANIM
	{ "FLARE_ANIM", ID_FLARE_ANIM },
	/// Object ID.
	// @mem LARA_SKIN
	{ "LARA_SKIN", ID_LARA_SKIN },
	/// Object ID.
	// @mem LARA_SKIN_JOINTS
	{ "LARA_SKIN_JOINTS", ID_LARA_SKIN_JOINTS },
	/// Object ID.
	// @mem LARA_SCREAM
	{ "LARA_SCREAM", ID_LARA_SCREAM },
	/// Object ID.
	// @mem LARA_CROSSBOW_LASER
	{ "LARA_CROSSBOW_LASER", ID_LARA_CROSSBOW_LASER },
	/// Object ID.
	// @mem LARA_REVOLVER_LASER
	{ "LARA_REVOLVER_LASER", ID_LARA_REVOLVER_LASER },
	/// Object ID.
	// @mem LARA_HOLSTERS
	{ "LARA_HOLSTERS", ID_LARA_HOLSTERS },
	/// Object ID.
	// @mem LARA_HOLSTERS_PISTOLS
	{ "LARA_HOLSTERS_PISTOLS", ID_LARA_HOLSTERS_PISTOLS },
	/// Object ID.
	// @mem LARA_HOLSTERS_UZIS
	{ "LARA_HOLSTERS_UZIS", ID_LARA_HOLSTERS_UZIS },
	/// Object ID.
	// @mem LARA_HOLSTERS_REVOLVER
	{ "LARA_HOLSTERS_REVOLVER", ID_LARA_HOLSTERS_REVOLVER },
	/// Object ID.
	// @mem LARA_SPEECH_HEAD1
	{ "LARA_SPEECH_HEAD1", ID_LARA_SPEECH_HEAD1 },
	/// Object ID.
	// @mem LARA_SPEECH_HEAD2
	{ "LARA_SPEECH_HEAD2", ID_LARA_SPEECH_HEAD2 },
	/// Object ID.
	// @mem LARA_SPEECH_HEAD3
	{ "LARA_SPEECH_HEAD3", ID_LARA_SPEECH_HEAD3 },
	/// Object ID.
	// @mem LARA_SPEECH_HEAD4
	{ "LARA_SPEECH_HEAD4", ID_LARA_SPEECH_HEAD4 },
	/// Object ID.
	// @mem ACTOR1_SPEECH_HEAD1
	{ "ACTOR1_SPEECH_HEAD1", ID_ACTOR1_SPEECH_HEAD1 },
	/// Object ID.
	// @mem ACTOR1_SPEECH_HEAD2
	{ "ACTOR1_SPEECH_HEAD2", ID_ACTOR1_SPEECH_HEAD2 },
	/// Object ID.
	// @mem ACTOR2_SPEECH_HEAD1
	{ "ACTOR2_SPEECH_HEAD1", ID_ACTOR2_SPEECH_HEAD1 },
	/// Object ID.
	// @mem ACTOR2_SPEECH_HEAD2
	{ "ACTOR2_SPEECH_HEAD2", ID_ACTOR2_SPEECH_HEAD2 },
	/// Object ID.
	// @mem LARA_BINOCULARS_MESH
	{ "LARA_BINOCULARS_MESH", ID_LARA_BINOCULARS_MESH },
	/// Object ID.
	// @mem LARA_EXTRA_MESH1
	{ "LARA_EXTRA_MESH1", ID_LARA_EXTRA_MESH1 },
	/// Object ID.
	// @mem LARA_EXTRA_MESH2
	{ "LARA_EXTRA_MESH2", ID_LARA_EXTRA_MESH2 },
	/// Object ID.
	// @mem LARA_WATER_MESH
	{ "LARA_WATER_MESH", ID_LARA_WATER_MESH },
	/// Object ID.
	// @mem LARA_PETROL_MESH
	{ "LARA_PETROL_MESH", ID_LARA_PETROL_MESH },
	/// Object ID.
	// @mem LARA_DIRT_MESH
	{ "LARA_DIRT_MESH", ID_LARA_DIRT_MESH },
	/// Object ID.
	// @mem LARA_CROWBAR_ANIM
	{ "LARA_CROWBAR_ANIM", ID_LARA_CROWBAR_ANIM },
	/// Object ID.
	// @mem LARA_TORCH_ANIM
	{ "LARA_TORCH_ANIM", ID_LARA_TORCH_ANIM },
	/// Object ID.
	// @mem HAIR_PRIMARY
	{ "HAIR_PRIMARY", ID_HAIR_PRIMARY },
	/// Object ID.
	// @mem HAIR_SECONDARY
	{ "HAIR_SECONDARY", ID_HAIR_SECONDARY },
	/// Object ID.
	// @mem SNOWMOBILE_LARA_ANIMS
	{ "SNOWMOBILE_LARA_ANIMS", ID_SNOWMOBILE_LARA_ANIMS },
	/// Object ID.
	// @mem SNOWMOBILE
	{ "SNOWMOBILE", ID_SNOWMOBILE },
	/// Object ID.
	// @mem QUAD_LARA_ANIMS
	{ "QUAD_LARA_ANIMS", ID_QUAD_LARA_ANIMS },
	/// Object ID.
	// @mem QUAD
	{ "QUAD", ID_QUAD },
	/// Object ID.
	// @mem SPEEDBOAT_LARA_ANIMS
	{ "SPEEDBOAT_LARA_ANIMS", ID_SPEEDBOAT_LARA_ANIMS },
	/// Object ID.
	// @mem SPEEDBOAT
	{ "SPEEDBOAT", ID_SPEEDBOAT },
	/// Object ID.
	// @mem KAYAK_LARA_ANIMS
	{ "KAYAK_LARA_ANIMS", ID_KAYAK_LARA_ANIMS },
	/// Object ID.
	// @mem KAYAK
	{ "KAYAK", ID_KAYAK },
	/// Object ID.
	// @mem UPV_LARA_ANIMS
	{ "UPV_LARA_ANIMS", ID_UPV_LARA_ANIMS },
	/// Object ID.
	// @mem UPV
	{ "UPV", ID_UPV },
	/// Object ID.
	// @mem MINECART_LARA_ANIMS
	{ "MINECART_LARA_ANIMS", ID_MINECART_LARA_ANIMS },
	/// Object ID.
	// @mem MINECART
	{ "MINECART", ID_MINECART },
	/// Object ID.
	// @mem JEEP_LARA_ANIMS
	{ "JEEP_LARA_ANIMS", ID_JEEP_LARA_ANIMS },
	/// Object ID.
	// @mem JEEP
	{ "JEEP", ID_JEEP },
	/// Object ID.
	// @mem MOTORBIKE_LARA_ANIMS
	{ "MOTORBIKE_LARA_ANIMS", ID_MOTORBIKE_LARA_ANIMS },
	/// Object ID.
	// @mem MOTORBIKE
	{ "MOTORBIKE", ID_MOTORBIKE },
	/// Object ID.
	// @mem RUBBER_BOAT_LARA_ANIMS
	{ "RUBBER_BOAT_LARA_ANIMS", ID_RUBBER_BOAT_LARA_ANIMS },
	/// Object ID.
	// @mem RUBBER_BOAT
	{ "RUBBER_BOAT", ID_RUBBER_BOAT },
	/// Object ID.
	// @mem LARA_BIGGUN_ANIM
	{ "LARA_BIGGUN_ANIM", ID_LARA_BIGGUN_ANIM },
	/// Object ID.
	// @mem BIGGUN
	{ "BIGGUN", ID_BIGGUN },
	/// Object ID.
	// @mem VEHICLE_SMASHABLE_FLOOR
	{ "VEHICLE_SMASHABLE_FLOOR", ID_VEHICLE_SMASHABLE_FLOOR },
	/// Object ID.
	// @mem VEHICLE_SMASHABLE_WALL
	{ "VEHICLE_SMASHABLE_WALL", ID_VEHICLE_SMASHABLE_WALL },
	/// Object ID.
	// @mem WOLF
	{ "WOLF", ID_WOLF },
	/// Object ID.
	// @mem BEAR
	{ "BEAR", ID_BEAR },
	/// Object ID.
	// @mem APE
	{ "APE", ID_APE },
	/// Object ID.
	// @mem SMALL_SPIDER
	{ "SMALL_SPIDER", ID_SMALL_SPIDER },
	/// Object ID.
	// @mem BIG_SPIDER
	{ "BIG_SPIDER", ID_BIG_SPIDER },
	/// Object ID.
	// @mem CROW
	{ "CROW", ID_CROW },
	/// Object ID.
	// @mem TIGER
	{ "TIGER", ID_TIGER },
	/// Object ID.
	// @mem EAGLE
	{ "EAGLE", ID_EAGLE },
	/// Object ID.
	// @mem RAPTOR
	{ "RAPTOR", ID_RAPTOR },
	/// Object ID.
	// @mem TYRANNOSAUR
	{ "TYRANNOSAUR", ID_TYRANNOSAUR },
	/// Object ID.
	// @mem COBRA
	{ "COBRA", ID_COBRA },
	/// Object ID.
	// @mem MONKEY
	{ "MONKEY", ID_MONKEY },
	/// Object ID.
	// @mem WHALE
	{ "WHALE", ID_WHALE },
	/// Object ID.
	// @mem COMPSOGNATHUS
	{ "COMPSOGNATHUS", ID_COMPSOGNATHUS },
	/// Object ID.
	// @mem FISH_EMITTER
	{ "FISH_EMITTER", ID_FISH_EMITTER },
	/// Object ID.
	// @mem RAT
	{ "RAT", ID_RAT },
	/// Object ID.
	// @mem BIG_RAT
	{ "BIG_RAT", ID_BIG_RAT },
	/// Object ID.
	// @mem CROCODILE
	{ "CROCODILE", ID_CROCODILE },
	/// Object ID.
	// @mem BAT
	{ "BAT", ID_BAT },
	/// Object ID.
	// @mem SPHINX
	{ "SPHINX", ID_SPHINX },
	/// Object ID.
	// @mem WILD_BOAR
	{ "WILD_BOAR", ID_WILD_BOAR },
	/// Object ID.
	// @mem HARPY
	{ "HARPY", ID_HARPY },
	/// Object ID.
	// @mem BIG_SCORPION
	{ "BIG_SCORPION", ID_BIG_SCORPION },
	/// Object ID.
	// @mem SMALL_SCORPION
	{ "SMALL_SCORPION", ID_SMALL_SCORPION },
	/// Object ID.
	// @mem BABOON_NORMAL
	{ "BABOON_NORMAL", ID_BABOON_NORMAL },
	/// Object ID.
	// @mem BABOON_INV
	{ "BABOON_INV", ID_BABOON_INV },
	/// Object ID.
	// @mem BABOON_SILENT
	{ "BABOON_SILENT", ID_BABOON_SILENT },
	/// Object ID.
	// @mem LITTLE_BEETLE
	{ "LITTLE_BEETLE", ID_LITTLE_BEETLE },
	/// Object ID.
	// @mem LOCUSTS
	{ "LOCUSTS", ID_LOCUSTS },
	/// Object ID.
	// @mem SHARK
	{ "SHARK", ID_SHARK },
	/// Object ID.
	// @mem HUSKIE
	{ "HUSKIE", ID_HUSKIE },
	/// Object ID.
	// @mem DOG
	{ "DOG", ID_DOG },
	/// Object ID.
	// @mem BATS_EMITTER
	{ "BATS_EMITTER", ID_BATS_EMITTER },
	/// Object ID.
	// @mem RATS_EMITTER
	{ "RATS_EMITTER", ID_RATS_EMITTER },
	/// Object ID.
	// @mem SPIDERS_EMITTER
	{ "SPIDERS_EMITTER", ID_SPIDERS_EMITTER },
	/// Object ID.
	// @mem LION
	{ "LION", ID_LION },
	/// Object ID.
	// @mem DOBERMAN
	{ "DOBERMAN", ID_DOBERMAN },
	/// Object ID.
	// @mem HAMMERHEAD
	{ "HAMMERHEAD", ID_HAMMERHEAD },
	/// Object ID.
	// @mem CROCODILE_GOD
	{ "CROCODILE_GOD", ID_CROCODILE_GOD },
	/// Object ID.
	// @mem LOCUSTS_EMITTER
	{ "LOCUSTS_EMITTER", ID_LOCUSTS_EMITTER },
	/// Object ID.
	// @mem SCUBA_HARPOON
	{ "SCUBA_HARPOON", ID_SCUBA_HARPOON },
	/// Object ID.
	// @mem SCUBA_DIVER
	{ "SCUBA_DIVER", ID_SCUBA_DIVER },
	/// Object ID.
	// @mem GOON_SILENCER1
	{ "GOON_SILENCER1", ID_GOON_SILENCER1 },
	/// Object ID.
	// @mem GOON_SILENCER2
	{ "GOON_SILENCER2", ID_GOON_SILENCER2 },
	/// Object ID.
	// @mem GOON_SILENCER3
	{ "GOON_SILENCER3", ID_GOON_SILENCER3 },
	/// Object ID.
	// @mem BARRACUDA
	{ "BARRACUDA", ID_BARRACUDA },
	/// Object ID.
	// @mem WORKER_SHOTGUN
	{ "WORKER_SHOTGUN", ID_WORKER_SHOTGUN },
	/// Object ID.
	// @mem WORKER_MACHINEGUN
	{ "WORKER_MACHINEGUN", ID_WORKER_MACHINEGUN },
	/// Object ID.
	// @mem WORKER_DUAL_REVOLVER
	{ "WORKER_DUAL_REVOLVER", ID_WORKER_DUAL_REVOLVER },
	/// Object ID.
	// @mem WORKER_FLAMETHROWER
	{ "WORKER_FLAMETHROWER", ID_WORKER_FLAMETHROWER },
	/// Object ID.
	// @mem MONK1
	{ "MONK1", ID_MONK1 },
	/// Object ID.
	// @mem MONK2
	{ "MONK2", ID_MONK2 },
	/// Object ID.
	// @mem KNIFETHROWER
	{ "KNIFETHROWER", ID_KNIFETHROWER },
	/// Object ID.
	// @mem KNIFETHROWER_KNIFE
	{ "KNIFETHROWER_KNIFE", ID_KNIFETHROWER_KNIFE },
	/// Object ID.
	// @mem MERCENARY_UZI
	{ "MERCENARY_UZI", ID_MERCENARY_UZI },
	/// Object ID.
	// @mem MERCENARY_AUTOPISTOLS1
	{ "MERCENARY_AUTOPISTOLS1", ID_MERCENARY_AUTOPISTOLS1 },
	/// Object ID.
	// @mem MERCENARY_AUTOPISTOLS2
	{ "MERCENARY_AUTOPISTOLS2", ID_MERCENARY_AUTOPISTOLS2 },
	/// Object ID.
	// @mem SNOWMOBILE_GUN
	{ "SNOWMOBILE_GUN", ID_SNOWMOBILE_GUN },
	/// Object ID.
	// @mem SNOWMOBILE_DRIVER
	{ "SNOWMOBILE_DRIVER", ID_SNOWMOBILE_DRIVER },
	/// Object ID.
	// @mem FLAMETHROWER_BADDY
	{ "FLAMETHROWER_BADDY", ID_FLAMETHROWER_BADDY },
	/// Object ID.
	// @mem TRIBESMAN_WITH_AX
	{ "TRIBESMAN_WITH_AX", ID_TRIBESMAN_WITH_AX },
	/// Object ID.
	// @mem TRIBESMAN_WITH_DARTS
	{ "TRIBESMAN_WITH_DARTS", ID_TRIBESMAN_WITH_DARTS },
	/// Object ID.
	// @mem MP_WITH_STICK
	{ "MP_WITH_STICK", ID_MP_WITH_STICK },
	/// Object ID.
	// @mem MP_WITH_GUN
	{ "MP_WITH_GUN", ID_MP_WITH_GUN },
	/// Object ID.
	// @mem BADDY1
	{ "BADDY1", ID_BADDY1 },
	/// Object ID.
	// @mem BADDY2
	{ "BADDY2", ID_BADDY2 },
	/// Object ID.
	// @mem SAS_CAIRO
	{ "SAS_CAIRO", ID_SAS_CAIRO },
	/// Object ID.
	// @mem SAS_DYING
	{ "SAS_DYING", ID_SAS_DYING },
	/// Object ID.
	// @mem SAS_CAPTAIN
	{ "SAS_CAPTAIN", ID_SAS_CAPTAIN },
	/// Object ID.
	// @mem SAS_DRAG_BLOKE
	{ "SAS_DRAG_BLOKE", ID_SAS_DRAG_BLOKE },
	/// Object ID.
	// @mem GUIDE
	{ "GUIDE", ID_GUIDE },
	/// Object ID.
	// @mem VON_CROY
	{ "VON_CROY", ID_VON_CROY },
	/// Object ID.
	// @mem TROOPS
	{ "TROOPS", ID_TROOPS },
	/// Object ID.
	// @mem SAS
	{ "SAS", ID_SAS },
	/// Object ID.
	// @mem SWAT
	{ "SWAT", ID_SWAT },
	/// Object ID.
	// @mem SWAT_PLUS
	{ "SWAT_PLUS", ID_SWAT_PLUS },
	/// Object ID.
	// @mem GUARD1
	{ "GUARD1", ID_GUARD1 },
	/// Object ID.
	// @mem GUARD_LASER
	{ "GUARD_LASER", ID_GUARD_LASER },
	/// Object ID.
	// @mem LARSON
	{ "LARSON", ID_LARSON },
	/// Object ID.
	// @mem PIERRE
	{ "PIERRE", ID_PIERRE },
	/// Object ID.
	// @mem MAFIA
	{ "MAFIA", ID_MAFIA },
	/// Object ID.
	// @mem MAFIA2
	{ "MAFIA2", ID_MAFIA2 },
	/// Object ID.
	// @mem GUARD2
	{ "GUARD2", ID_GUARD2 },
	/// Object ID.
	// @mem GUARD3
	{ "GUARD3", ID_GUARD3 },
	/// Object ID.
	// @mem GLADIATOR
	{ "GLADIATOR", ID_GLADIATOR },
	/// Object ID.
	// @mem CYBORG
	{ "CYBORG", ID_CYBORG },
	/// Object ID.
	// @mem SNIPER
	{ "SNIPER", ID_SNIPER },
	/// Object ID.
	// @mem CHEF
	{ "CHEF", ID_CHEF },
	/// Object ID.
	// @mem KOLD
	{ "KOLD", ID_KOLD },
	/// Object ID.
	// @mem WINGED_MUMMY
	{ "WINGED_MUMMY", ID_WINGED_MUMMY },
	/// Object ID.
	// @mem CENTAUR_MUTANT
	{ "CENTAUR_MUTANT", ID_CENTAUR_MUTANT },
	/// Object ID.
	// @mem DOPPELGANGER
	{ "DOPPELGANGER", ID_DOPPELGANGER },
	/// Object ID.
	// @mem NATLA
	{ "NATLA", ID_NATLA },
	/// Object ID.
	// @mem GIANT_MUTANT
	{ "GIANT_MUTANT", ID_GIANT_MUTANT },
	/// Object ID.
	// @mem PROJ_SHARD
	{ "PROJ_SHARD", ID_PROJ_SHARD },
	/// Object ID.
	// @mem PROJ_BOMB
	{ "PROJ_BOMB", ID_PROJ_BOMB },
	/// Object ID.
	// @mem YETI
	{ "YETI", ID_YETI },
	/// Object ID.
	// @mem BIRDMONSTER
	{ "BIRDMONSTER", ID_BIRDMONSTER },
	/// Object ID.
	// @mem MARCO_BARTOLI
	{ "MARCO_BARTOLI", ID_MARCO_BARTOLI },
	/// Object ID.
	// @mem DRAGON_FRONT
	{ "DRAGON_FRONT", ID_DRAGON_FRONT },
	/// Object ID.
	// @mem DRAGON_BACK
	{ "DRAGON_BACK", ID_DRAGON_BACK },
	/// Object ID.
	// @mem DRAGON_BONE_FRONT
	{ "DRAGON_BONE_FRONT", ID_DRAGON_BONE_FRONT },
	/// Object ID.
	// @mem DRAGON_BONE_BACK
	{ "DRAGON_BONE_BACK", ID_DRAGON_BONE_BACK },
	/// Object ID.
	// @mem SPHERE_OF_DOOM
	{ "SPHERE_OF_DOOM", ID_SPHERE_OF_DOOM },
	/// Object ID.
	// @mem SPHERE_OF_DOOM2
	{ "SPHERE_OF_DOOM2", ID_SPHERE_OF_DOOM2 },
	/// Object ID.
	// @mem SPHERE_OF_DOOM3
	{ "SPHERE_OF_DOOM3", ID_SPHERE_OF_DOOM3 },
	/// Object ID.
	// @mem COWBOY
	{ "COWBOY", ID_COWBOY },
	/// Object ID.
	// @mem SPEAR_GUARDIAN
	{ "SPEAR_GUARDIAN", ID_SPEAR_GUARDIAN },
	/// Object ID.
	// @mem SPEAR_GUARDIAN_STATUE
	{ "SPEAR_GUARDIAN_STATUE", ID_SPEAR_GUARDIAN_STATUE },
	/// Object ID.
	// @mem SWORD_GUARDIAN
	{ "SWORD_GUARDIAN", ID_SWORD_GUARDIAN },
	/// Object ID.
	// @mem SWORD_GUARDIAN_STATUE
	{ "SWORD_GUARDIAN_STATUE", ID_SWORD_GUARDIAN_STATUE },
	/// Object ID.
	// @mem SHIVA
	{ "SHIVA", ID_SHIVA },
	/// Object ID.
	// @mem SHIVA_STATUE
	{ "SHIVA_STATUE", ID_SHIVA_STATUE },
	/// Object ID.
	// @mem WILLARD
	{ "WILLARD", ID_WILLARD },
	/// Object ID.
	// @mem CIVVY
	{ "CIVVY", ID_CIVVY },
	/// Object ID.
	// @mem MUTANT2
	{ "MUTANT2", ID_MUTANT2 },
	/// Object ID.
	// @mem LIZARD
	{ "LIZARD", ID_LIZARD },
	/// Object ID.
	// @mem TONY_BOSS
	{ "TONY_BOSS", ID_TONY_BOSS },
	/// Object ID.
	// @mem TONY_BOSS_FLAME
	{ "TONY_BOSS_FLAME", ID_TONY_BOSS_FLAME },
	/// Object ID.
	// @mem PUNA_BOSS
	{ "PUNA_BOSS", ID_PUNA_BOSS },
	/// Object ID.
	// @mem SOPHIA_LEIGH_BOSS
	{ "SOPHIA_LEIGH_BOSS", ID_SOPHIA_LEIGH_BOSS },
	/// Object ID.
	// @mem LASER_BOLT
	{ "LASER_BOLT", ID_LASER_BOLT },
	/// Object ID.
	// @mem SKELETON
	{ "SKELETON", ID_SKELETON },
	/// Object ID.
	// @mem MUMMY
	{ "MUMMY", ID_MUMMY },
	/// Object ID.
	// @mem ENEMY_JEEP
	{ "ENEMY_JEEP", ID_ENEMY_JEEP },
	/// Object ID.
	// @mem HORSE
	{ "HORSE", ID_HORSE },
	/// Object ID.
	// @mem HORSEMAN
	{ "HORSEMAN", ID_HORSEMAN },
	/// Object ID.
	// @mem DEMIGOD1
	{ "DEMIGOD1", ID_DEMIGOD1 },
	/// Object ID.
	// @mem DEMIGOD2
	{ "DEMIGOD2", ID_DEMIGOD2 },
	/// Object ID.
	// @mem DEMIGOD3
	{ "DEMIGOD3", ID_DEMIGOD3 },
	/// Object ID.
	// @mem SETHA
	{ "SETHA", ID_SETHA },
	/// Object ID.
	// @mem KNIGHT_TEMPLAR
	{ "KNIGHT_TEMPLAR", ID_KNIGHT_TEMPLAR },
	/// Object ID.
	// @mem AHMET
	{ "AHMET", ID_AHMET },
	/// Object ID.
	// @mem BIG_BEETLE
	{ "BIG_BEETLE", ID_BIG_BEETLE },
	/// Object ID.
	// @mem JEAN_YVES
	{ "JEAN_YVES", ID_JEAN_YVES },
	/// Object ID.
	// @mem WRAITH1
	{ "WRAITH1", ID_WRAITH1 },
	/// Object ID.
	// @mem WRAITH2
	{ "WRAITH2", ID_WRAITH2 },
	/// Object ID.
	// @mem WRAITH3
	{ "WRAITH3", ID_WRAITH3 },
	/// Object ID.
	// @mem WRAITH4
	{ "WRAITH4", ID_WRAITH4 },
	/// Object ID.
	// @mem LARA_DOUBLE
	{ "LARA_DOUBLE", ID_LARA_DOUBLE },
	/// Object ID.
	// @mem HYDRA
	{ "HYDRA", ID_HYDRA },
	/// Object ID.
	// @mem LASERHEAD
	{ "LASERHEAD", ID_LASERHEAD },
	/// Object ID.
	// @mem SCIENTIST
	{ "SCIENTIST", ID_SCIENTIST },
	/// Object ID.
	// @mem MERCENARY
	{ "MERCENARY", ID_MERCENARY },
	/// Object ID.
	// @mem WILLOWISP
	{ "WILLOWISP", ID_WILLOWISP },
	/// Object ID.
	// @mem INVISIBLE_GHOST
	{ "INVISIBLE_GHOST", ID_INVISIBLE_GHOST },
	/// Object ID.
	// @mem REAPER
	{ "REAPER", ID_REAPER },
	/// Object ID.
	// @mem BROWN_BEAST
	{ "BROWN_BEAST", ID_BROWN_BEAST },
	/// Object ID.
	// @mem ATTACK_SUB
	{ "ATTACK_SUB", ID_ATTACK_SUB },
	/// Object ID.
	// @mem IMP
	{ "IMP", ID_IMP },
	/// Object ID.
	// @mem IMP_ROCK
	{ "IMP_ROCK", ID_IMP_ROCK },
	/// Object ID.
	// @mem GUNSHIP
	{ "GUNSHIP", ID_GUNSHIP },
	/// Object ID.
	// @mem AUTO_GUN_VCI
	{ "AUTO_GUN_VCI", ID_AUTO_GUN_VCI },
	/// Object ID.
	// @mem ROMAN_GOD1
	{ "ROMAN_GOD1", ID_ROMAN_GOD1 },
	/// Object ID.
	// @mem ROMAN_GOD2
	{ "ROMAN_GOD2", ID_ROMAN_GOD2 },
	/// Object ID.
	// @mem LAGOON_WITCH
	{ "LAGOON_WITCH", ID_LAGOON_WITCH },
	/// Object ID.
	// @mem BOSS_SHIELD
	{ "BOSS_SHIELD", ID_BOSS_SHIELD },
	/// Object ID.
	// @mem BOSS_EXPLOSION_SHOCKWAVE
	{ "BOSS_EXPLOSION_SHOCKWAVE", ID_BOSS_EXPLOSION_SHOCKWAVE },
	/// Object ID.
	// @mem BOSS_EXPLOSION_RING
	{ "BOSS_EXPLOSION_RING", ID_BOSS_EXPLOSION_RING },
	/// Object ID.
	// @mem CLAW_MUTANT
	{ "CLAW_MUTANT", ID_CLAW_MUTANT },
	/// Object ID.
	// @mem WASP_MUTANT
	{ "WASP_MUTANT", ID_WASP_MUTANT },
	/// Object ID.
	// @mem TWIN_AUTO_GUN
	{ "TWIN_AUTO_GUN", ID_TWIN_AUTO_GUN },
	/// Object ID.
	// @mem SKATEBOARD
	{ "SKATEBOARD", ID_SKATEBOARD },
	/// Object ID.
	// @mem SKATEBOARD_KID
	{ "SKATEBOARD_KID", ID_SKATEBOARD_KID },
	/// Object ID.
	// @mem WINSTON
	{ "WINSTON", ID_WINSTON },
	/// Object ID.
	// @mem SEAL_MUTANT
	{ "SEAL_MUTANT", ID_SEAL_MUTANT },
	/// Object ID.
	// @mem SPRINGBOARD
	{ "SPRINGBOARD", ID_SPRINGBOARD },
	/// Object ID.
	// @mem ROLLING_SPINDLE
	{ "ROLLING_SPINDLE", ID_ROLLING_SPINDLE },
	/// Object ID.
	// @mem DISK_SHOOTER
	{ "DISK_SHOOTER", ID_DISK_SHOOTER },
	/// Object ID.
	// @mem DISK
	{ "DISK", ID_DISK },
	/// Object ID.
	// @mem WALL_MOUNTED_BLADE
	{ "WALL_MOUNTED_BLADE", ID_WALL_MOUNTED_BLADE },
	/// Object ID.
	// @mem STATUE_WITH_BLADE
	{ "STATUE_WITH_BLADE", ID_STATUE_WITH_BLADE },
	/// Object ID.
	// @mem COG
	{ "COG", ID_COG },
	/// Object ID.
	// @mem SPIKEBALL
	{ "SPIKEBALL", ID_SPIKEBALL },
	/// Object ID.
	// @mem FLOOR_4BLADES
	{ "FLOOR_4BLADES", ID_FLOOR_4BLADES },
	/// Object ID.
	// @mem CEILING_4BLADES
	{ "CEILING_4BLADES", ID_CEILING_4BLADES },
	/// Object ID.
	// @mem CATWALK_BLADE
	{ "CATWALK_BLADE", ID_CATWALK_BLADE },
	/// Object ID.
	// @mem SETH_BLADE
	{ "SETH_BLADE", ID_SETH_BLADE },
	/// Object ID.
	// @mem PLINTH_BLADE
	{ "PLINTH_BLADE", ID_PLINTH_BLADE },
	/// Object ID.
	// @mem SLICER_DICER
	{ "SLICER_DICER", ID_SLICER_DICER },
	/// Object ID.
	// @mem BIRD_BLADE
	{ "BIRD_BLADE", ID_BIRD_BLADE },
	/// Object ID.
	// @mem CHAIN
	{ "CHAIN", ID_CHAIN },
	/// Object ID.
	// @mem PLOUGH
	{ "PLOUGH", ID_PLOUGH },
	/// Object ID.
	// @mem STARGATE
	{ "STARGATE", ID_STARGATE },
	/// Object ID.
	// @mem SPIKY_FLOOR
	{ "SPIKY_FLOOR", ID_SPIKY_FLOOR },
	/// Object ID.
	// @mem SPIKY_WALL
	{ "SPIKY_WALL", ID_SPIKY_WALL },
	/// Object ID.
	// @mem SPIKY_CEILING
	{ "SPIKY_CEILING", ID_SPIKY_CEILING },
	/// Object ID.
	// @mem TEETH_SPIKES
	{ "TEETH_SPIKES", ID_TEETH_SPIKES },
	/// Object ID.
	// @mem JOBY_SPIKES
	{ "JOBY_SPIKES", ID_JOBY_SPIKES },
	/// Object ID.
	// @mem SENTRY_GUN
	{ "SENTRY_GUN", ID_SENTRY_GUN },
	/// Object ID.
	// @mem MAPPER
	{ "MAPPER", ID_MAPPER },
	/// Object ID.
	// @mem MOVING_BLADE
	{ "MOVING_BLADE", ID_MOVING_BLADE },
	/// Object ID.
	// @mem ELEMENT_PUZZLE
	{ "ELEMENT_PUZZLE", ID_ELEMENT_PUZZLE },
	/// Object ID.
	// @mem LIGHTING_CONDUCTOR
	{ "LIGHTING_CONDUCTOR", ID_LIGHTING_CONDUCTOR },
	/// Object ID.
	// @mem HAMMER
	{ "HAMMER", ID_HAMMER },
	/// Object ID.
	// @mem OBELISK
	{ "OBELISK", ID_OBELISK },
	/// Object ID.
	// @mem WHEEL_OF_FORTUNE
	{ "WHEEL_OF_FORTUNE", ID_WHEEL_OF_FORTUNE },
	/// Object ID.
	// @mem GAME_PIECE1
	{ "GAME_PIECE1", ID_GAME_PIECE1 },
	/// Object ID.
	// @mem GAME_PIECE2
	{ "GAME_PIECE2", ID_GAME_PIECE2 },
	/// Object ID.
	// @mem GAME_PIECE3
	{ "GAME_PIECE3", ID_GAME_PIECE3 },
	/// Object ID.
	// @mem RAISING_COG
	{ "RAISING_COG", ID_RAISING_COG },
	/// Object ID.
	// @mem MINE
	{ "MINE", ID_MINE },
	/// Object ID.
	// @mem SCALES
	{ "SCALES", ID_SCALES },
	/// Object ID.
	// @mem ROME_HAMMER
	{ "ROME_HAMMER", ID_ROME_HAMMER },
	/// Object ID.
	// @mem FLAME
	{ "FLAME", ID_FLAME },
	/// Object ID.
	// @mem FLAME_EMITTER
	{ "FLAME_EMITTER", ID_FLAME_EMITTER },
	/// Object ID.
	// @mem FLAME_EMITTER2
	{ "FLAME_EMITTER2", ID_FLAME_EMITTER2 },
	/// Object ID.
	// @mem FLAME_EMITTER3
	{ "FLAME_EMITTER3", ID_FLAME_EMITTER3 },
	/// Object ID.
	// @mem BURNING_ROOTS
	{ "BURNING_ROOTS", ID_BURNING_ROOTS },
	/// Object ID.
	// @mem ROPE
	{ "ROPE", ID_ROPE },
	/// Object ID.
	// @mem FIREROPE
	{ "FIREROPE", ID_FIREROPE },
	/// Object ID.
	// @mem POLEROPE
	{ "POLEROPE", ID_POLEROPE },
	/// Object ID.
	// @mem ELECTRICAL_CABLES
	{ "ELECTRICAL_CABLES", ID_ELECTRICAL_CABLES },
	/// Object ID.
	// @mem BURNING_FLOOR
	{ "BURNING_FLOOR", ID_BURNING_FLOOR },
	/// Object ID.
	// @mem DARTS
	{ "DARTS", ID_DARTS },
	/// Object ID.
	// @mem DART_EMITTER
	{ "DART_EMITTER", ID_DART_EMITTER },
	/// Object ID.
	// @mem HOMING_DART_EMITTER
	{ "HOMING_DART_EMITTER", ID_HOMING_DART_EMITTER },
	/// Object ID.
	// @mem FALLING_CEILING
	{ "FALLING_CEILING", ID_FALLING_CEILING },
	/// Object ID.
	// @mem FALLING_BLOCK
	{ "FALLING_BLOCK", ID_FALLING_BLOCK },
	/// Object ID.
	// @mem FALLING_BLOCK2
	{ "FALLING_BLOCK2", ID_FALLING_BLOCK2 },
	/// Object ID.
	// @mem CRUMBLING_FLOOR
	{ "CRUMBLING_FLOOR", ID_CRUMBLING_FLOOR },
	/// Object ID.
	// @mem TRAPDOOR1
	{ "TRAPDOOR1", ID_TRAPDOOR1 },
	/// Object ID.
	// @mem TRAPDOOR2
	{ "TRAPDOOR2", ID_TRAPDOOR2 },
	/// Object ID.
	// @mem TRAPDOOR3
	{ "TRAPDOOR3", ID_TRAPDOOR3 },
	/// Object ID.
	// @mem FLOOR_TRAPDOOR1
	{ "FLOOR_TRAPDOOR1", ID_FLOOR_TRAPDOOR1 },
	/// Object ID.
	// @mem FLOOR_TRAPDOOR2
	{ "FLOOR_TRAPDOOR2", ID_FLOOR_TRAPDOOR2 },
	/// Object ID.
	// @mem CEILING_TRAPDOOR1
	{ "CEILING_TRAPDOOR1", ID_CEILING_TRAPDOOR1 },
	/// Object ID.
	// @mem CEILING_TRAPDOOR2
	{ "CEILING_TRAPDOOR2", ID_CEILING_TRAPDOOR2 },
	/// Object ID.
	// @mem SCALING_TRAPDOOR
	{ "SCALING_TRAPDOOR", ID_SCALING_TRAPDOOR },
	/// Object ID.
	// @mem ROLLINGBALL
	{ "ROLLINGBALL", ID_ROLLINGBALL },
	/// Object ID.
	// @mem ROLLINGBARREL
	{ "ROLLINGBARREL", ID_ROLLINGBARREL },
	/// Object ID.
	// @mem PROPELLER_H
	{ "PROPELLER_H", ID_PROPELLER_H },
	/// Object ID.
	// @mem PROPELLER_V
	{ "PROPELLER_V", ID_PROPELLER_V },
	/// Object ID.
	// @mem ONEBLOCK_PLATFORM
	{ "ONEBLOCK_PLATFORM", ID_ONEBLOCK_PLATFORM },
	/// Object ID.
	// @mem TWOBLOCK_PLATFORM
	{ "TWOBLOCK_PLATFORM", ID_TWOBLOCK_PLATFORM },
	/// Object ID.
	// @mem RAISING_BLOCK1
	{ "RAISING_BLOCK1", ID_RAISING_BLOCK1 },
	/// Object ID.
	// @mem RAISING_BLOCK2
	{ "RAISING_BLOCK2", ID_RAISING_BLOCK2 },
	/// Object ID.
	// @mem RAISING_BLOCK3
	{ "RAISING_BLOCK3", ID_RAISING_BLOCK3 },
	/// Object ID.
	// @mem RAISING_BLOCK4
	{ "RAISING_BLOCK4", ID_RAISING_BLOCK4 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT1
	{ "PUSHABLE_OBJECT1", ID_PUSHABLE_OBJECT1 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT2
	{ "PUSHABLE_OBJECT2", ID_PUSHABLE_OBJECT2 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT3
	{ "PUSHABLE_OBJECT3", ID_PUSHABLE_OBJECT3 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT4
	{ "PUSHABLE_OBJECT4", ID_PUSHABLE_OBJECT4 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT5
	{ "PUSHABLE_OBJECT5", ID_PUSHABLE_OBJECT5 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT6
	{ "PUSHABLE_OBJECT6", ID_PUSHABLE_OBJECT6 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT7
	{ "PUSHABLE_OBJECT7", ID_PUSHABLE_OBJECT7 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT8
	{ "PUSHABLE_OBJECT8", ID_PUSHABLE_OBJECT8 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT9
	{ "PUSHABLE_OBJECT9", ID_PUSHABLE_OBJECT9 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT10
	{ "PUSHABLE_OBJECT10", ID_PUSHABLE_OBJECT10 },
	/// Object ID.
	// @mem WRECKING_BALL
	{ "WRECKING_BALL", ID_WRECKING_BALL },
	/// Object ID.
	// @mem ZIPLINE_HANDLE
	{ "ZIPLINE_HANDLE", ID_ZIPLINE_HANDLE },
	/// Object ID.
	// @mem TORPEDO
	{ "TORPEDO", ID_TORPEDO },
	/// Object ID.
	// @mem CHAFF
	{ "CHAFF", ID_CHAFF },
	/// Object ID.
	// @mem ELECTRIC_FENCE
	{ "ELECTRIC_FENCE", ID_ELECTRIC_FENCE },
	/// Object ID.
	// @mem LIFT
	{ "LIFT", ID_LIFT },
	/// Object ID.
	// @mem TIGHT_ROPE
	{ "TIGHT_ROPE", ID_TIGHT_ROPE },
	/// Object ID.
	// @mem PARALLEL_BARS
	{ "PARALLEL_BARS", ID_PARALLEL_BARS },
	/// Object ID.
	// @mem XRAY_CONTROLLER
	{ "XRAY_CONTROLLER", ID_XRAY_CONTROLLER },
	/// Object ID.
	// @mem PORTAL
	{ "PORTAL", ID_PORTAL },
	/// Object ID.
	// @mem GEN_SLOT1
	{ "GEN_SLOT1", ID_GEN_SLOT1 },
	/// Object ID.
	// @mem GEN_SLOT2
	{ "GEN_SLOT2", ID_GEN_SLOT2 },
	/// Object ID.
	// @mem GEN_SLOT3
	{ "GEN_SLOT3", ID_GEN_SLOT3 },
	/// Object ID.
	// @mem GEN_SLOT4
	{ "GEN_SLOT4", ID_GEN_SLOT4 },
	/// Object ID.
	// @mem SEARCH_OBJECT1
	{ "SEARCH_OBJECT1", ID_SEARCH_OBJECT1 },
	/// Object ID.
	// @mem SEARCH_OBJECT2
	{ "SEARCH_OBJECT2", ID_SEARCH_OBJECT2 },
	/// Object ID.
	// @mem SEARCH_OBJECT3
	{ "SEARCH_OBJECT3", ID_SEARCH_OBJECT3 },
	/// Object ID.
	// @mem SEARCH_OBJECT4
	{ "SEARCH_OBJECT4", ID_SEARCH_OBJECT4 },
	/// Object ID.
	// @mem SARCOPHAGUS
	{ "SARCOPHAGUS", ID_SARCOPHAGUS },
	/// Object ID.
	// @mem ENEMY_PIECE
	{ "ENEMY_PIECE", ID_ENEMY_PIECE },
	/// Object ID.
	// @mem EXPANDING_PLATFORM
	{ "EXPANDING_PLATFORM", ID_EXPANDING_PLATFORM },
	/// Object ID.
	// @mem SQUISHY_BLOCK_HORIZONTAL
	{ "SQUISHY_BLOCK_HORIZONTAL", ID_SQUISHY_BLOCK_HORIZONTAL },
	/// Object ID.
	// @mem SQUISHY_BLOCK_VERTICAL
	{ "SQUISHY_BLOCK_VERTICAL", ID_SQUISHY_BLOCK_VERTICAL },
	/// Object ID.
	// @mem LASER_BEAM
	{ "LASER_BEAM", ID_LASER_BEAM },
	/// Object ID.
	// @mem MINE_DETECTOR
	{ "MINE_DETECTOR", ID_MINE_DETECTOR },
	/// Object ID.
	// @mem MAP
	{ "MAP", ID_MAP },
	/// Object ID.
	// @mem SECRET_MAP
	{ "SECRET_MAP", ID_SECRET_MAP },
	/// Object ID.
	// @mem SETH_DOOR
	{ "SETH_DOOR", ID_SETH_DOOR },
	/// Object ID.
	// @mem HORUS_STATUE
	{ "HORUS_STATUE", ID_HORUS_STATUE },
	/// Object ID.
	// @mem STATUE_PLINTH
	{ "STATUE_PLINTH", ID_STATUE_PLINTH },
	/// Object ID.
	// @mem CLASSIC_ROLLING_BALL
	{ "CLASSIC_ROLLING_BALL", ID_CLASSIC_ROLLING_BALL },
	/// Object ID.
	// @mem BIG_ROLLING_BALL
	{ "BIG_ROLLING_BALL", ID_BIG_ROLLING_BALL },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE1
	{ "PUSHABLE_OBJECT_CLIMBABLE1", ID_PUSHABLE_OBJECT_CLIMBABLE1 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE2
	{ "PUSHABLE_OBJECT_CLIMBABLE2", ID_PUSHABLE_OBJECT_CLIMBABLE2 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE3
	{ "PUSHABLE_OBJECT_CLIMBABLE3", ID_PUSHABLE_OBJECT_CLIMBABLE3 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE4
	{ "PUSHABLE_OBJECT_CLIMBABLE4", ID_PUSHABLE_OBJECT_CLIMBABLE4 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE5
	{ "PUSHABLE_OBJECT_CLIMBABLE5", ID_PUSHABLE_OBJECT_CLIMBABLE5 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE6
	{ "PUSHABLE_OBJECT_CLIMBABLE6", ID_PUSHABLE_OBJECT_CLIMBABLE6 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE7
	{ "PUSHABLE_OBJECT_CLIMBABLE7", ID_PUSHABLE_OBJECT_CLIMBABLE7 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE8
	{ "PUSHABLE_OBJECT_CLIMBABLE8", ID_PUSHABLE_OBJECT_CLIMBABLE8 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE9
	{ "PUSHABLE_OBJECT_CLIMBABLE9", ID_PUSHABLE_OBJECT_CLIMBABLE9 },
	/// Object ID.
	// @mem PUSHABLE_OBJECT_CLIMBABLE10
	{ "PUSHABLE_OBJECT_CLIMBABLE10", ID_PUSHABLE_OBJECT_CLIMBABLE10 },
	/// Object ID.
	// @mem TRAIN
	{ "TRAIN", ID_TRAIN },
	/// Object ID.
	// @mem EXPLOSION
	{ "EXPLOSION", ID_EXPLOSION },
	/// Object ID.
	// @mem DAMOCLES_SWORD
	{ "DAMOCLES_SWORD", ID_DAMOCLES_SWORD },
	/// Object ID.
	// @mem ELECTRIC_CLEANER
	{ "ELECTRIC_CLEANER", ID_ELECTRIC_CLEANER },
	/// Object ID.
	// @mem SLAMMING_DOORS
	{ "SLAMMING_DOORS", ID_SLAMMING_DOORS },
	/// Object ID.
	// @mem SWINGING_BLADE
	{ "SWINGING_BLADE", ID_SWINGING_BLADE },
	/// Object ID.
	// @mem ELECTRIC_BALL
	{ "ELECTRIC_BALL", ID_ELECTRIC_BALL },
	/// Object ID.
	// @mem ELECTRIC_BALL_IMPACT_POINT
	{ "ELECTRIC_BALL_IMPACT_POINT", ID_ELECTRIC_BALL_IMPACT_POINT },
	/// Object ID.
	// @mem THOR_HAMMER_HANDLE
	{ "THOR_HAMMER_HANDLE", ID_THOR_HAMMER_HANDLE },
	/// Object ID.
	// @mem THOR_HAMMER_HEAD
	{ "THOR_HAMMER_HEAD", ID_THOR_HAMMER_HEAD },
	/// Object ID.
	// @mem MOVING_LASER
	{ "MOVING_LASER", ID_MOVING_LASER },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM1
	{ "PUZZLE_ITEM1", ID_PUZZLE_ITEM1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM2
	{ "PUZZLE_ITEM2", ID_PUZZLE_ITEM2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM3
	{ "PUZZLE_ITEM3", ID_PUZZLE_ITEM3 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM4
	{ "PUZZLE_ITEM4", ID_PUZZLE_ITEM4 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM5
	{ "PUZZLE_ITEM5", ID_PUZZLE_ITEM5 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM6
	{ "PUZZLE_ITEM6", ID_PUZZLE_ITEM6 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM7
	{ "PUZZLE_ITEM7", ID_PUZZLE_ITEM7 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM8
	{ "PUZZLE_ITEM8", ID_PUZZLE_ITEM8 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM9
	{ "PUZZLE_ITEM9", ID_PUZZLE_ITEM9 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM10
	{ "PUZZLE_ITEM10", ID_PUZZLE_ITEM10 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM11
	{ "PUZZLE_ITEM11", ID_PUZZLE_ITEM11 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM12
	{ "PUZZLE_ITEM12", ID_PUZZLE_ITEM12 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM13
	{ "PUZZLE_ITEM13", ID_PUZZLE_ITEM13 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM14
	{ "PUZZLE_ITEM14", ID_PUZZLE_ITEM14 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM15
	{ "PUZZLE_ITEM15", ID_PUZZLE_ITEM15 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM16
	{ "PUZZLE_ITEM16", ID_PUZZLE_ITEM16 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM1_COMBO1
	{ "PUZZLE_ITEM1_COMBO1", ID_PUZZLE_ITEM1_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM1_COMBO2
	{ "PUZZLE_ITEM1_COMBO2", ID_PUZZLE_ITEM1_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM2_COMBO1
	{ "PUZZLE_ITEM2_COMBO1", ID_PUZZLE_ITEM2_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM2_COMBO2
	{ "PUZZLE_ITEM2_COMBO2", ID_PUZZLE_ITEM2_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM3_COMBO1
	{ "PUZZLE_ITEM3_COMBO1", ID_PUZZLE_ITEM3_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM3_COMBO2
	{ "PUZZLE_ITEM3_COMBO2", ID_PUZZLE_ITEM3_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM4_COMBO1
	{ "PUZZLE_ITEM4_COMBO1", ID_PUZZLE_ITEM4_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM4_COMBO2
	{ "PUZZLE_ITEM4_COMBO2", ID_PUZZLE_ITEM4_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM5_COMBO1
	{ "PUZZLE_ITEM5_COMBO1", ID_PUZZLE_ITEM5_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM5_COMBO2
	{ "PUZZLE_ITEM5_COMBO2", ID_PUZZLE_ITEM5_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM6_COMBO1
	{ "PUZZLE_ITEM6_COMBO1", ID_PUZZLE_ITEM6_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM6_COMBO2
	{ "PUZZLE_ITEM6_COMBO2", ID_PUZZLE_ITEM6_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM7_COMBO1
	{ "PUZZLE_ITEM7_COMBO1", ID_PUZZLE_ITEM7_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM7_COMBO2
	{ "PUZZLE_ITEM7_COMBO2", ID_PUZZLE_ITEM7_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM8_COMBO1
	{ "PUZZLE_ITEM8_COMBO1", ID_PUZZLE_ITEM8_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM8_COMBO2
	{ "PUZZLE_ITEM8_COMBO2", ID_PUZZLE_ITEM8_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM9_COMBO1
	{ "PUZZLE_ITEM9_COMBO1", ID_PUZZLE_ITEM9_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM9_COMBO2
	{ "PUZZLE_ITEM9_COMBO2", ID_PUZZLE_ITEM9_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM10_COMBO1
	{ "PUZZLE_ITEM10_COMBO1", ID_PUZZLE_ITEM10_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM10_COMBO2
	{ "PUZZLE_ITEM10_COMBO2", ID_PUZZLE_ITEM10_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM11_COMBO1
	{ "PUZZLE_ITEM11_COMBO1", ID_PUZZLE_ITEM11_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM11_COMBO2
	{ "PUZZLE_ITEM11_COMBO2", ID_PUZZLE_ITEM11_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM12_COMBO1
	{ "PUZZLE_ITEM12_COMBO1", ID_PUZZLE_ITEM12_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM12_COMBO2
	{ "PUZZLE_ITEM12_COMBO2", ID_PUZZLE_ITEM12_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM13_COMBO1
	{ "PUZZLE_ITEM13_COMBO1", ID_PUZZLE_ITEM13_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM13_COMBO2
	{ "PUZZLE_ITEM13_COMBO2", ID_PUZZLE_ITEM13_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM14_COMBO1
	{ "PUZZLE_ITEM14_COMBO1", ID_PUZZLE_ITEM14_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM14_COMBO2
	{ "PUZZLE_ITEM14_COMBO2", ID_PUZZLE_ITEM14_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM15_COMBO1
	{ "PUZZLE_ITEM15_COMBO1", ID_PUZZLE_ITEM15_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM15_COMBO2
	{ "PUZZLE_ITEM15_COMBO2", ID_PUZZLE_ITEM15_COMBO2 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM16_COMBO1
	{ "PUZZLE_ITEM16_COMBO1", ID_PUZZLE_ITEM16_COMBO1 },
	/// Pickup Object ID.
	// @mem PUZZLE_ITEM16_COMBO2
	{ "PUZZLE_ITEM16_COMBO2", ID_PUZZLE_ITEM16_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM1
	{ "KEY_ITEM1", ID_KEY_ITEM1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM2
	{ "KEY_ITEM2", ID_KEY_ITEM2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM3
	{ "KEY_ITEM3", ID_KEY_ITEM3 },
	/// Pickup Object ID.
	// @mem KEY_ITEM4
	{ "KEY_ITEM4", ID_KEY_ITEM4 },
	/// Pickup Object ID.
	// @mem KEY_ITEM5
	{ "KEY_ITEM5", ID_KEY_ITEM5 },
	/// Pickup Object ID.
	// @mem KEY_ITEM6
	{ "KEY_ITEM6", ID_KEY_ITEM6 },
	/// Pickup Object ID.
	// @mem KEY_ITEM7
	{ "KEY_ITEM7", ID_KEY_ITEM7 },
	/// Pickup Object ID.
	// @mem KEY_ITEM8
	{ "KEY_ITEM8", ID_KEY_ITEM8 },
	/// Pickup Object ID.
	// @mem KEY_ITEM9
	{ "KEY_ITEM9", ID_KEY_ITEM9 },
	/// Pickup Object ID.
	// @mem KEY_ITEM10
	{ "KEY_ITEM10", ID_KEY_ITEM10 },
	/// Pickup Object ID.
	// @mem KEY_ITEM11
	{ "KEY_ITEM11", ID_KEY_ITEM11 },
	/// Pickup Object ID.
	// @mem KEY_ITEM12
	{ "KEY_ITEM12", ID_KEY_ITEM12 },
	/// Pickup Object ID.
	// @mem KEY_ITEM13
	{ "KEY_ITEM13", ID_KEY_ITEM13 },
	/// Pickup Object ID.
	// @mem KEY_ITEM14
	{ "KEY_ITEM14", ID_KEY_ITEM14 },
	/// Pickup Object ID.
	// @mem KEY_ITEM15
	{ "KEY_ITEM15", ID_KEY_ITEM15 },
	/// Pickup Object ID.
	// @mem KEY_ITEM16
	{ "KEY_ITEM16", ID_KEY_ITEM16 },
	/// Pickup Object ID.
	// @mem KEY_ITEM1_COMBO1
	{ "KEY_ITEM1_COMBO1", ID_KEY_ITEM1_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM1_COMBO2
	{ "KEY_ITEM1_COMBO2", ID_KEY_ITEM1_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM2_COMBO1
	{ "KEY_ITEM2_COMBO1", ID_KEY_ITEM2_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM2_COMBO2
	{ "KEY_ITEM2_COMBO2", ID_KEY_ITEM2_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM3_COMBO1
	{ "KEY_ITEM3_COMBO1", ID_KEY_ITEM3_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM3_COMBO2
	{ "KEY_ITEM3_COMBO2", ID_KEY_ITEM3_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM4_COMBO1
	{ "KEY_ITEM4_COMBO1", ID_KEY_ITEM4_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM4_COMBO2
	{ "KEY_ITEM4_COMBO2", ID_KEY_ITEM4_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM5_COMBO1
	{ "KEY_ITEM5_COMBO1", ID_KEY_ITEM5_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM5_COMBO2
	{ "KEY_ITEM5_COMBO2", ID_KEY_ITEM5_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM6_COMBO1
	{ "KEY_ITEM6_COMBO1", ID_KEY_ITEM6_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM6_COMBO2
	{ "KEY_ITEM6_COMBO2", ID_KEY_ITEM6_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM7_COMBO1
	{ "KEY_ITEM7_COMBO1", ID_KEY_ITEM7_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM7_COMBO2
	{ "KEY_ITEM7_COMBO2", ID_KEY_ITEM7_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM8_COMBO1
	{ "KEY_ITEM8_COMBO1", ID_KEY_ITEM8_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM8_COMBO2
	{ "KEY_ITEM8_COMBO2", ID_KEY_ITEM8_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM9_COMBO1
	{ "KEY_ITEM9_COMBO1", ID_KEY_ITEM9_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM9_COMBO2
	{ "KEY_ITEM9_COMBO2", ID_KEY_ITEM9_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM10_COMBO1
	{ "KEY_ITEM10_COMBO1", ID_KEY_ITEM10_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM10_COMBO2
	{ "KEY_ITEM10_COMBO2", ID_KEY_ITEM10_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM11_COMBO1
	{ "KEY_ITEM11_COMBO1", ID_KEY_ITEM11_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM11_COMBO2
	{ "KEY_ITEM11_COMBO2", ID_KEY_ITEM11_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM12_COMBO1
	{ "KEY_ITEM12_COMBO1", ID_KEY_ITEM12_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM12_COMBO2
	{ "KEY_ITEM12_COMBO2", ID_KEY_ITEM12_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM13_COMBO1
	{ "KEY_ITEM13_COMBO1", ID_KEY_ITEM13_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM13_COMBO2
	{ "KEY_ITEM13_COMBO2", ID_KEY_ITEM13_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM14_COMBO1
	{ "KEY_ITEM14_COMBO1", ID_KEY_ITEM14_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM14_COMBO2
	{ "KEY_ITEM14_COMBO2", ID_KEY_ITEM14_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM15_COMBO1
	{ "KEY_ITEM15_COMBO1", ID_KEY_ITEM15_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM15_COMBO2
	{ "KEY_ITEM15_COMBO2", ID_KEY_ITEM15_COMBO2 },
	/// Pickup Object ID.
	// @mem KEY_ITEM16_COMBO1
	{ "KEY_ITEM16_COMBO1", ID_KEY_ITEM16_COMBO1 },
	/// Pickup Object ID.
	// @mem KEY_ITEM16_COMBO2
	{ "KEY_ITEM16_COMBO2", ID_KEY_ITEM16_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM1
	{ "PICKUP_ITEM1", ID_PICKUP_ITEM1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM2
	{ "PICKUP_ITEM2", ID_PICKUP_ITEM2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM3
	{ "PICKUP_ITEM3", ID_PICKUP_ITEM3 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM4
	{ "PICKUP_ITEM4", ID_PICKUP_ITEM4 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM5
	{ "PICKUP_ITEM5", ID_PICKUP_ITEM5 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM6
	{ "PICKUP_ITEM6", ID_PICKUP_ITEM6 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM7
	{ "PICKUP_ITEM7", ID_PICKUP_ITEM7 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM8
	{ "PICKUP_ITEM8", ID_PICKUP_ITEM8 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM9
	{ "PICKUP_ITEM9", ID_PICKUP_ITEM9 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM10
	{ "PICKUP_ITEM10", ID_PICKUP_ITEM10 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM11
	{ "PICKUP_ITEM11", ID_PICKUP_ITEM11 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM12
	{ "PICKUP_ITEM12", ID_PICKUP_ITEM12 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM13
	{ "PICKUP_ITEM13", ID_PICKUP_ITEM13 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM14
	{ "PICKUP_ITEM14", ID_PICKUP_ITEM14 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM15
	{ "PICKUP_ITEM15", ID_PICKUP_ITEM15 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM16
	{ "PICKUP_ITEM16", ID_PICKUP_ITEM16 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM1_COMBO1
	{ "PICKUP_ITEM1_COMBO1", ID_PICKUP_ITEM1_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM1_COMBO2
	{ "PICKUP_ITEM1_COMBO2", ID_PICKUP_ITEM1_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM2_COMBO1
	{ "PICKUP_ITEM2_COMBO1", ID_PICKUP_ITEM2_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM2_COMBO2
	{ "PICKUP_ITEM2_COMBO2", ID_PICKUP_ITEM2_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM3_COMBO1
	{ "PICKUP_ITEM3_COMBO1", ID_PICKUP_ITEM3_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM3_COMBO2
	{ "PICKUP_ITEM3_COMBO2", ID_PICKUP_ITEM3_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM4_COMBO1
	{ "PICKUP_ITEM4_COMBO1", ID_PICKUP_ITEM4_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM4_COMBO2
	{ "PICKUP_ITEM4_COMBO2", ID_PICKUP_ITEM4_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM5_COMBO1
	{ "PICKUP_ITEM5_COMBO1", ID_PICKUP_ITEM5_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM5_COMBO2
	{ "PICKUP_ITEM5_COMBO2", ID_PICKUP_ITEM5_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM6_COMBO1
	{ "PICKUP_ITEM6_COMBO1", ID_PICKUP_ITEM6_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM6_COMBO2
	{ "PICKUP_ITEM6_COMBO2", ID_PICKUP_ITEM6_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM7_COMBO1
	{ "PICKUP_ITEM7_COMBO1", ID_PICKUP_ITEM7_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM7_COMBO2
	{ "PICKUP_ITEM7_COMBO2", ID_PICKUP_ITEM7_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM8_COMBO1
	{ "PICKUP_ITEM8_COMBO1", ID_PICKUP_ITEM8_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM8_COMBO2
	{ "PICKUP_ITEM8_COMBO2", ID_PICKUP_ITEM8_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM9_COMBO1
	{ "PICKUP_ITEM9_COMBO1", ID_PICKUP_ITEM9_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM9_COMBO2
	{ "PICKUP_ITEM9_COMBO2", ID_PICKUP_ITEM9_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM10_COMBO1
	{ "PICKUP_ITEM10_COMBO1", ID_PICKUP_ITEM10_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM10_COMBO2
	{ "PICKUP_ITEM10_COMBO2", ID_PICKUP_ITEM10_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM11_COMBO1
	{ "PICKUP_ITEM11_COMBO1", ID_PICKUP_ITEM11_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM11_COMBO2
	{ "PICKUP_ITEM11_COMBO2", ID_PICKUP_ITEM11_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM12_COMBO1
	{ "PICKUP_ITEM12_COMBO1", ID_PICKUP_ITEM12_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM12_COMBO2
	{ "PICKUP_ITEM12_COMBO2", ID_PICKUP_ITEM12_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM13_COMBO1
	{ "PICKUP_ITEM13_COMBO1", ID_PICKUP_ITEM13_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM13_COMBO2
	{ "PICKUP_ITEM13_COMBO2", ID_PICKUP_ITEM13_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM14_COMBO1
	{ "PICKUP_ITEM14_COMBO1", ID_PICKUP_ITEM14_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM14_COMBO2
	{ "PICKUP_ITEM14_COMBO2", ID_PICKUP_ITEM14_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM15_COMBO1
	{ "PICKUP_ITEM15_COMBO1", ID_PICKUP_ITEM15_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM15_COMBO2
	{ "PICKUP_ITEM15_COMBO2", ID_PICKUP_ITEM15_COMBO2 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM16_COMBO1
	{ "PICKUP_ITEM16_COMBO1", ID_PICKUP_ITEM16_COMBO1 },
	/// Pickup Object ID.
	// @mem PICKUP_ITEM16_COMBO2
	{ "PICKUP_ITEM16_COMBO2", ID_PICKUP_ITEM16_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE1
	{ "EXAMINE1", ID_EXAMINE1 },
	/// Pickup Object ID.
	// @mem EXAMINE2
	{ "EXAMINE2", ID_EXAMINE2 },
	/// Pickup Object ID.
	// @mem EXAMINE3
	{ "EXAMINE3", ID_EXAMINE3 },
	/// Pickup Object ID.
	// @mem EXAMINE4
	{ "EXAMINE4", ID_EXAMINE4 },
	/// Pickup Object ID.
	// @mem EXAMINE5
	{ "EXAMINE5", ID_EXAMINE5 },
	/// Pickup Object ID.
	// @mem EXAMINE6
	{ "EXAMINE6", ID_EXAMINE6 },
	/// Pickup Object ID.
	// @mem EXAMINE7
	{ "EXAMINE7", ID_EXAMINE7 },
	/// Pickup Object ID.
	// @mem EXAMINE8
	{ "EXAMINE8", ID_EXAMINE8 },
	/// Pickup Object ID.
	// @mem EXAMINE1_COMBO1
	{ "EXAMINE1_COMBO1", ID_EXAMINE1_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE1_COMBO2
	{ "EXAMINE1_COMBO2", ID_EXAMINE1_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE2_COMBO1
	{ "EXAMINE2_COMBO1", ID_EXAMINE2_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE2_COMBO2
	{ "EXAMINE2_COMBO2", ID_EXAMINE2_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE3_COMBO1
	{ "EXAMINE3_COMBO1", ID_EXAMINE3_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE3_COMBO2
	{ "EXAMINE3_COMBO2", ID_EXAMINE3_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE4_COMBO1
	{ "EXAMINE4_COMBO1", ID_EXAMINE4_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE4_COMBO2
	{ "EXAMINE4_COMBO2", ID_EXAMINE4_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE5_COMBO1
	{ "EXAMINE5_COMBO1", ID_EXAMINE5_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE5_COMBO2
	{ "EXAMINE5_COMBO2", ID_EXAMINE5_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE6_COMBO1
	{ "EXAMINE6_COMBO1", ID_EXAMINE6_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE6_COMBO2
	{ "EXAMINE6_COMBO2", ID_EXAMINE6_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE7_COMBO1
	{ "EXAMINE7_COMBO1", ID_EXAMINE7_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE7_COMBO2
	{ "EXAMINE7_COMBO2", ID_EXAMINE7_COMBO2 },
	/// Pickup Object ID.
	// @mem EXAMINE8_COMBO1
	{ "EXAMINE8_COMBO1", ID_EXAMINE8_COMBO1 },
	/// Pickup Object ID.
	// @mem EXAMINE8_COMBO2
	{ "EXAMINE8_COMBO2", ID_EXAMINE8_COMBO2 },
	/// Object ID.
	// @mem PUZZLE_HOLE1
	{ "PUZZLE_HOLE1", ID_PUZZLE_HOLE1 },
	/// Object ID.
	// @mem PUZZLE_HOLE2
	{ "PUZZLE_HOLE2", ID_PUZZLE_HOLE2 },
	/// Object ID.
	// @mem PUZZLE_HOLE3
	{ "PUZZLE_HOLE3", ID_PUZZLE_HOLE3 },
	/// Object ID.
	// @mem PUZZLE_HOLE4
	{ "PUZZLE_HOLE4", ID_PUZZLE_HOLE4 },
	/// Object ID.
	// @mem PUZZLE_HOLE5
	{ "PUZZLE_HOLE5", ID_PUZZLE_HOLE5 },
	/// Object ID.
	// @mem PUZZLE_HOLE6
	{ "PUZZLE_HOLE6", ID_PUZZLE_HOLE6 },
	/// Object ID.
	// @mem PUZZLE_HOLE7
	{ "PUZZLE_HOLE7", ID_PUZZLE_HOLE7 },
	/// Object ID.
	// @mem PUZZLE_HOLE8
	{ "PUZZLE_HOLE8", ID_PUZZLE_HOLE8 },
	/// Object ID.
	// @mem PUZZLE_HOLE9
	{ "PUZZLE_HOLE9", ID_PUZZLE_HOLE9 },
	/// Object ID.
	// @mem PUZZLE_HOLE10
	{ "PUZZLE_HOLE10", ID_PUZZLE_HOLE10 },
	/// Object ID.
	// @mem PUZZLE_HOLE11
	{ "PUZZLE_HOLE11", ID_PUZZLE_HOLE11 },
	/// Object ID.
	// @mem PUZZLE_HOLE12
	{ "PUZZLE_HOLE12", ID_PUZZLE_HOLE12 },
	/// Object ID.
	// @mem PUZZLE_HOLE13
	{ "PUZZLE_HOLE13", ID_PUZZLE_HOLE13 },
	/// Object ID.
	// @mem PUZZLE_HOLE14
	{ "PUZZLE_HOLE14", ID_PUZZLE_HOLE14 },
	/// Object ID.
	// @mem PUZZLE_HOLE15
	{ "PUZZLE_HOLE15", ID_PUZZLE_HOLE15 },
	/// Object ID.
	// @mem PUZZLE_HOLE16
	{ "PUZZLE_HOLE16", ID_PUZZLE_HOLE16 },
	/// Object ID.
	// @mem PUZZLE_DONE1
	{ "PUZZLE_DONE1", ID_PUZZLE_DONE1 },
	/// Object ID.
	// @mem PUZZLE_DONE2
	{ "PUZZLE_DONE2", ID_PUZZLE_DONE2 },
	/// Object ID.
	// @mem PUZZLE_DONE3
	{ "PUZZLE_DONE3", ID_PUZZLE_DONE3 },
	/// Object ID.
	// @mem PUZZLE_DONE4
	{ "PUZZLE_DONE4", ID_PUZZLE_DONE4 },
	/// Object ID.
	// @mem PUZZLE_DONE5
	{ "PUZZLE_DONE5", ID_PUZZLE_DONE5 },
	/// Object ID.
	// @mem PUZZLE_DONE6
	{ "PUZZLE_DONE6", ID_PUZZLE_DONE6 },
	/// Object ID.
	// @mem PUZZLE_DONE7
	{ "PUZZLE_DONE7", ID_PUZZLE_DONE7 },
	/// Object ID.
	// @mem PUZZLE_DONE8
	{ "PUZZLE_DONE8", ID_PUZZLE_DONE8 },
	/// Object ID.
	// @mem PUZZLE_DONE9
	{ "PUZZLE_DONE9", ID_PUZZLE_DONE9 },
	/// Object ID.
	// @mem PUZZLE_DONE10
	{ "PUZZLE_DONE10", ID_PUZZLE_DONE10 },
	/// Object ID.
	// @mem PUZZLE_DONE11
	{ "PUZZLE_DONE11", ID_PUZZLE_DONE11 },
	/// Object ID.
	// @mem PUZZLE_DONE12
	{ "PUZZLE_DONE12", ID_PUZZLE_DONE12 },
	/// Object ID.
	// @mem PUZZLE_DONE13
	{ "PUZZLE_DONE13", ID_PUZZLE_DONE13 },
	/// Object ID.
	// @mem PUZZLE_DONE14
	{ "PUZZLE_DONE14", ID_PUZZLE_DONE14 },
	/// Object ID.
	// @mem PUZZLE_DONE15
	{ "PUZZLE_DONE15", ID_PUZZLE_DONE15 },
	/// Object ID.
	// @mem PUZZLE_DONE16
	{ "PUZZLE_DONE16", ID_PUZZLE_DONE16 },
	/// Object ID.
	// @mem KEY_HOLE1
	{ "KEY_HOLE1", ID_KEY_HOLE1 },
	/// Object ID.
	// @mem KEY_HOLE2
	{ "KEY_HOLE2", ID_KEY_HOLE2 },
	/// Object ID.
	// @mem KEY_HOLE3
	{ "KEY_HOLE3", ID_KEY_HOLE3 },
	/// Object ID.
	// @mem KEY_HOLE4
	{ "KEY_HOLE4", ID_KEY_HOLE4 },
	/// Object ID.
	// @mem KEY_HOLE5
	{ "KEY_HOLE5", ID_KEY_HOLE5 },
	/// Object ID.
	// @mem KEY_HOLE6
	{ "KEY_HOLE6", ID_KEY_HOLE6 },
	/// Object ID.
	// @mem KEY_HOLE7
	{ "KEY_HOLE7", ID_KEY_HOLE7 },
	/// Object ID.
	// @mem KEY_HOLE8
	{ "KEY_HOLE8", ID_KEY_HOLE8 },
	/// Object ID.
	// @mem KEY_HOLE9
	{ "KEY_HOLE9", ID_KEY_HOLE9 },
	/// Object ID.
	// @mem KEY_HOLE10
	{ "KEY_HOLE10", ID_KEY_HOLE10 },
	/// Object ID.
	// @mem KEY_HOLE11
	{ "KEY_HOLE11", ID_KEY_HOLE11 },
	/// Object ID.
	// @mem KEY_HOLE12
	{ "KEY_HOLE12", ID_KEY_HOLE12 },
	/// Object ID.
	// @mem KEY_HOLE13
	{ "KEY_HOLE13", ID_KEY_HOLE13 },
	/// Object ID.
	// @mem KEY_HOLE14
	{ "KEY_HOLE14", ID_KEY_HOLE14 },
	/// Object ID.
	// @mem KEY_HOLE15
	{ "KEY_HOLE15", ID_KEY_HOLE15 },
	/// Object ID.
	// @mem KEY_HOLE16
	{ "KEY_HOLE16", ID_KEY_HOLE16 },
	/// Object ID.
	// @mem WATERSKIN1_EMPTY
	{ "WATERSKIN1_EMPTY", ID_WATERSKIN1_EMPTY },
	/// Object ID.
	// @mem WATERSKIN1_1
	{ "WATERSKIN1_1", ID_WATERSKIN1_1 },
	/// Object ID.
	// @mem WATERSKIN1_2
	{ "WATERSKIN1_2", ID_WATERSKIN1_2 },
	/// Object ID.
	// @mem WATERSKIN1_3
	{ "WATERSKIN1_3", ID_WATERSKIN1_3 },
	/// Object ID.
	// @mem WATERSKIN2_EMPTY
	{ "WATERSKIN2_EMPTY", ID_WATERSKIN2_EMPTY },
	/// Object ID.
	// @mem WATERSKIN2_1
	{ "WATERSKIN2_1", ID_WATERSKIN2_1 },
	/// Object ID.
	// @mem WATERSKIN2_2
	{ "WATERSKIN2_2", ID_WATERSKIN2_2 },
	/// Object ID.
	// @mem WATERSKIN2_3
	{ "WATERSKIN2_3", ID_WATERSKIN2_3 },
	/// Object ID.
	// @mem WATERSKIN2_4
	{ "WATERSKIN2_4", ID_WATERSKIN2_4 },
	/// Object ID.
	// @mem WATERSKIN2_5
	{ "WATERSKIN2_5", ID_WATERSKIN2_5 },
	/// Pickup Object ID.
	// @mem HAMMER_ITEM
	{ "HAMMER_ITEM", ID_HAMMER_ITEM },
	/// Pickup Object ID.
	// @mem CROWBAR_ITEM
	{ "CROWBAR_ITEM", ID_CROWBAR_ITEM },
	/// Pickup Object ID.
	// @mem BURNING_TORCH_ITEM
	{ "BURNING_TORCH_ITEM", ID_BURNING_TORCH_ITEM },
	/// Object ID.
	// @mem CLOCKWORK_BEETLE
	{ "CLOCKWORK_BEETLE", ID_CLOCKWORK_BEETLE },
	/// Object ID.
	// @mem CLOCKWORK_BEETLE_COMBO1
	{ "CLOCKWORK_BEETLE_COMBO1", ID_CLOCKWORK_BEETLE_COMBO1 },
	/// Object ID.
	// @mem CLOCKWORK_BEETLE_COMBO2
	{ "CLOCKWORK_BEETLE_COMBO2", ID_CLOCKWORK_BEETLE_COMBO2 },
	/// Object ID.
	// @mem SWITCH_TYPE1
	{ "SWITCH_TYPE1", ID_SWITCH_TYPE1 },
	/// Object ID.
	// @mem SWITCH_TYPE2
	{ "SWITCH_TYPE2", ID_SWITCH_TYPE2 },
	/// Object ID.
	// @mem SWITCH_TYPE3
	{ "SWITCH_TYPE3", ID_SWITCH_TYPE3 },
	/// Object ID.
	// @mem SWITCH_TYPE4
	{ "SWITCH_TYPE4", ID_SWITCH_TYPE4 },
	/// Object ID.
	// @mem SWITCH_TYPE5
	{ "SWITCH_TYPE5", ID_SWITCH_TYPE5 },
	/// Object ID.
	// @mem SWITCH_TYPE6
	{ "SWITCH_TYPE6", ID_SWITCH_TYPE6 },
	/// Object ID.
	// @mem SWITCH_TYPE7
	{ "SWITCH_TYPE7", ID_SWITCH_TYPE7 },
	/// Object ID.
	// @mem SWITCH_TYPE8
	{ "SWITCH_TYPE8", ID_SWITCH_TYPE8 },
	/// Object ID.
	// @mem SWITCH_TYPE9
	{ "SWITCH_TYPE9", ID_SWITCH_TYPE9 },
	/// Object ID.
	// @mem SWITCH_TYPE10
	{ "SWITCH_TYPE10", ID_SWITCH_TYPE10 },
	/// Object ID.
	// @mem SWITCH_TYPE11
	{ "SWITCH_TYPE11", ID_SWITCH_TYPE11 },
	/// Object ID.
	// @mem SWITCH_TYPE12
	{ "SWITCH_TYPE12", ID_SWITCH_TYPE12 },
	/// Object ID.
	// @mem SWITCH_TYPE13
	{ "SWITCH_TYPE13", ID_SWITCH_TYPE13 },
	/// Object ID.
	// @mem SWITCH_TYPE14
	{ "SWITCH_TYPE14", ID_SWITCH_TYPE14 },
	/// Object ID.
	// @mem SWITCH_TYPE15
	{ "SWITCH_TYPE15", ID_SWITCH_TYPE15 },
	/// Object ID.
	// @mem SWITCH_TYPE16
	{ "SWITCH_TYPE16", ID_SWITCH_TYPE16 },
	/// Object ID.
	// @mem SHOOT_SWITCH1
	{ "SHOOT_SWITCH1", ID_SHOOT_SWITCH1 },
	/// Object ID.
	// @mem SHOOT_SWITCH2
	{ "SHOOT_SWITCH2", ID_SHOOT_SWITCH2 },
	/// Object ID.
	// @mem SHOOT_SWITCH3
	{ "SHOOT_SWITCH3", ID_SHOOT_SWITCH3 },
	/// Object ID.
	// @mem SHOOT_SWITCH4
	{ "SHOOT_SWITCH4", ID_SHOOT_SWITCH4 },
	/// Object ID.
	// @mem AIRLOCK_SWITCH
	{ "AIRLOCK_SWITCH", ID_AIRLOCK_SWITCH },
	/// Object ID.
	// @mem UNDERWATER_WALL_SWITCH1
	{ "UNDERWATER_WALL_SWITCH1", ID_UNDERWATER_WALL_SWITCH1 },
	/// Object ID.
	// @mem UNDERWATER_WALL_SWITCH2
	{ "UNDERWATER_WALL_SWITCH2", ID_UNDERWATER_WALL_SWITCH2 },
	/// Object ID.
	// @mem UNDERWATER_CEILING_SWITCH1
	{ "UNDERWATER_CEILING_SWITCH1", ID_UNDERWATER_CEILING_SWITCH1 },
	/// Object ID.
	// @mem UNDERWATER_CEILING_SWITCH2
	{ "UNDERWATER_CEILING_SWITCH2", ID_UNDERWATER_CEILING_SWITCH2 },
	/// Object ID.
	// @mem TURN_SWITCH
	{ "TURN_SWITCH", ID_TURN_SWITCH },
	/// Object ID.
	// @mem COG_SWITCH
	{ "COG_SWITCH", ID_COG_SWITCH },
	/// Object ID.
	// @mem LEVER_SWITCH
	{ "LEVER_SWITCH", ID_LEVER_SWITCH },
	/// Object ID.
	// @mem JUMP_SWITCH
	{ "JUMP_SWITCH", ID_JUMP_SWITCH },
	/// Object ID.
	// @mem CROWBAR_SWITCH
	{ "CROWBAR_SWITCH", ID_CROWBAR_SWITCH },
	/// Object ID.
	// @mem PULLEY
	{ "PULLEY", ID_PULLEY },
	/// Object ID.
	// @mem CROWDOVE_SWITCH
	{ "CROWDOVE_SWITCH", ID_CROWDOVE_SWITCH },
	/// Object ID.
	// @mem MINECART_SWITCH
	{ "MINECART_SWITCH", ID_MINECART_SWITCH },
	/// Object ID.
	// @mem DOOR_TYPE1
	{ "DOOR_TYPE1", ID_DOOR_TYPE1 },
	/// Object ID.
	// @mem DOOR_TYPE2
	{ "DOOR_TYPE2", ID_DOOR_TYPE2 },
	/// Object ID.
	// @mem DOOR_TYPE3
	{ "DOOR_TYPE3", ID_DOOR_TYPE3 },
	/// Object ID.
	// @mem DOOR_TYPE4
	{ "DOOR_TYPE4", ID_DOOR_TYPE4 },
	/// Object ID.
	// @mem DOOR_TYPE5
	{ "DOOR_TYPE5", ID_DOOR_TYPE5 },
	/// Object ID.
	// @mem DOOR_TYPE6
	{ "DOOR_TYPE6", ID_DOOR_TYPE6 },
	/// Object ID.
	// @mem DOOR_TYPE7
	{ "DOOR_TYPE7", ID_DOOR_TYPE7 },
	/// Object ID.
	// @mem DOOR_TYPE8
	{ "DOOR_TYPE8", ID_DOOR_TYPE8 },
	/// Object ID.
	// @mem DOOR_TYPE9
	{ "DOOR_TYPE9", ID_DOOR_TYPE9 },
	/// Object ID.
	// @mem DOOR_TYPE10
	{ "DOOR_TYPE10", ID_DOOR_TYPE10 },
	/// Object ID.
	// @mem DOOR_TYPE11
	{ "DOOR_TYPE11", ID_DOOR_TYPE11 },
	/// Object ID.
	// @mem DOOR_TYPE12
	{ "DOOR_TYPE12", ID_DOOR_TYPE12 },
	/// Object ID.
	// @mem DOOR_TYPE13
	{ "DOOR_TYPE13", ID_DOOR_TYPE13 },
	/// Object ID.
	// @mem DOOR_TYPE14
	{ "DOOR_TYPE14", ID_DOOR_TYPE14 },
	/// Object ID.
	// @mem DOOR_TYPE15
	{ "DOOR_TYPE15", ID_DOOR_TYPE15 },
	/// Object ID.
	// @mem DOOR_TYPE16
	{ "DOOR_TYPE16", ID_DOOR_TYPE16 },
	/// Object ID.
	// @mem DOOR_TYPE17
	{ "DOOR_TYPE17", ID_DOOR_TYPE17 },
	/// Object ID.
	// @mem DOOR_TYPE18
	{ "DOOR_TYPE18", ID_DOOR_TYPE18 },
	/// Object ID.
	// @mem DOOR_TYPE19
	{ "DOOR_TYPE19", ID_DOOR_TYPE19 },
	/// Object ID.
	// @mem DOOR_TYPE20
	{ "DOOR_TYPE20", ID_DOOR_TYPE20 },
	/// Object ID.
	// @mem DOOR_TYPE21
	{ "DOOR_TYPE21", ID_DOOR_TYPE21 },
	/// Object ID.
	// @mem DOOR_TYPE22
	{ "DOOR_TYPE22", ID_DOOR_TYPE22 },
	/// Object ID.
	// @mem DOOR_TYPE23
	{ "DOOR_TYPE23", ID_DOOR_TYPE23 },
	/// Object ID.
	// @mem DOOR_TYPE24
	{ "DOOR_TYPE24", ID_DOOR_TYPE24 },
	/// Object ID.
	// @mem DOOR_TYPE25
	{ "DOOR_TYPE25", ID_DOOR_TYPE25 },
	/// Object ID.
	// @mem DOOR_TYPE26
	{ "DOOR_TYPE26", ID_DOOR_TYPE26 },
	/// Object ID.
	// @mem DOOR_TYPE27
	{ "DOOR_TYPE27", ID_DOOR_TYPE27 },
	/// Object ID.
	// @mem DOOR_TYPE28
	{ "DOOR_TYPE28", ID_DOOR_TYPE28 },
	/// Object ID.
	// @mem DOOR_TYPE29
	{ "DOOR_TYPE29", ID_DOOR_TYPE29 },
	/// Object ID.
	// @mem DOOR_TYPE30
	{ "DOOR_TYPE30", ID_DOOR_TYPE30 },
	/// Object ID.
	// @mem LIFT_DOORS1
	{ "LIFT_DOORS1", ID_LIFT_DOORS1 },
	/// Object ID.
	// @mem LIFT_DOORS2
	{ "LIFT_DOORS2", ID_LIFT_DOORS2 },
	/// Object ID.
	// @mem PUSHPULL_DOOR1
	{ "PUSHPULL_DOOR1", ID_PUSHPULL_DOOR1 },
	/// Object ID.
	// @mem PUSHPULL_DOOR2
	{ "PUSHPULL_DOOR2", ID_PUSHPULL_DOOR2 },
	/// Object ID.
	// @mem PUSHPULL_DOOR3
	{ "PUSHPULL_DOOR3", ID_PUSHPULL_DOOR3 },
	/// Object ID.
	// @mem PUSHPULL_DOOR4
	{ "PUSHPULL_DOOR4", ID_PUSHPULL_DOOR4 },
	/// Object ID.
	// @mem KICK_DOOR1
	{ "KICK_DOOR1", ID_KICK_DOOR1 },
	/// Object ID.
	// @mem KICK_DOOR2
	{ "KICK_DOOR2", ID_KICK_DOOR2 },
	/// Object ID.
	// @mem KICK_DOOR3
	{ "KICK_DOOR3", ID_KICK_DOOR3 },
	/// Object ID.
	// @mem KICK_DOOR4
	{ "KICK_DOOR4", ID_KICK_DOOR4 },
	/// Object ID.
	// @mem UNDERWATER_DOOR1
	{ "UNDERWATER_DOOR1", ID_UNDERWATER_DOOR1 },
	/// Object ID.
	// @mem UNDERWATER_DOOR2
	{ "UNDERWATER_DOOR2", ID_UNDERWATER_DOOR2 },
	/// Object ID.
	// @mem UNDERWATER_DOOR3
	{ "UNDERWATER_DOOR3", ID_UNDERWATER_DOOR3 },
	/// Object ID.
	// @mem UNDERWATER_DOOR4
	{ "UNDERWATER_DOOR4", ID_UNDERWATER_DOOR4 },
	/// Object ID.
	// @mem DOUBLE_DOORS1
	{ "DOUBLE_DOORS1", ID_DOUBLE_DOORS1 },
	/// Object ID.
	// @mem DOUBLE_DOORS2
	{ "DOUBLE_DOORS2", ID_DOUBLE_DOORS2 },
	/// Object ID.
	// @mem DOUBLE_DOORS3
	{ "DOUBLE_DOORS3", ID_DOUBLE_DOORS3 },
	/// Object ID.
	// @mem DOUBLE_DOORS4
	{ "DOUBLE_DOORS4", ID_DOUBLE_DOORS4 },
	/// Object ID.
	// @mem SEQUENCE_DOOR1
	{ "SEQUENCE_DOOR1", ID_SEQUENCE_DOOR1 },
	/// Object ID.
	// @mem SEQUENCE_SWITCH1
	{ "SEQUENCE_SWITCH1", ID_SEQUENCE_SWITCH1 },
	/// Object ID.
	// @mem SEQUENCE_SWITCH2
	{ "SEQUENCE_SWITCH2", ID_SEQUENCE_SWITCH2 },
	/// Object ID.
	// @mem SEQUENCE_SWITCH3
	{ "SEQUENCE_SWITCH3", ID_SEQUENCE_SWITCH3 },
	/// Object ID.
	// @mem STEEL_DOOR
	{ "STEEL_DOOR", ID_STEEL_DOOR },
	/// Object ID.
	// @mem GOD_HEAD
	{ "GOD_HEAD", ID_GOD_HEAD },
	/// Object ID.
	// @mem BREAKABLE_WALL
	{ "BREAKABLE_WALL", ID_BREAKABLE_WALL },
	/// Pickup Object ID.
	// @mem PISTOLS_ITEM
	{ "PISTOLS_ITEM", ID_PISTOLS_ITEM },
	/// Pickup Object ID.
	// @mem PISTOLS_AMMO_ITEM
	{ "PISTOLS_AMMO_ITEM", ID_PISTOLS_AMMO_ITEM },
	/// Pickup Object ID.
	// @mem UZI_ITEM
	{ "UZI_ITEM", ID_UZI_ITEM },
	/// Pickup Object ID.
	// @mem UZI_AMMO_ITEM
	{ "UZI_AMMO_ITEM", ID_UZI_AMMO_ITEM },
	/// Pickup Object ID.
	// @mem SHOTGUN_ITEM
	{ "SHOTGUN_ITEM", ID_SHOTGUN_ITEM },
	/// Pickup Object ID.
	// @mem SHOTGUN_AMMO1_ITEM
	{ "SHOTGUN_AMMO1_ITEM", ID_SHOTGUN_AMMO1_ITEM },
	/// Pickup Object ID.
	// @mem SHOTGUN_AMMO2_ITEM
	{ "SHOTGUN_AMMO2_ITEM", ID_SHOTGUN_AMMO2_ITEM },
	/// Pickup Object ID.
	// @mem REVOLVER_ITEM
	{ "REVOLVER_ITEM", ID_REVOLVER_ITEM },
	/// Pickup Object ID.
	// @mem REVOLVER_AMMO_ITEM
	{ "REVOLVER_AMMO_ITEM", ID_REVOLVER_AMMO_ITEM },
	/// Pickup Object ID.
	// @mem CROSSBOW_ITEM
	{ "CROSSBOW_ITEM", ID_CROSSBOW_ITEM },
	/// Pickup Object ID.
	// @mem CROSSBOW_AMMO1_ITEM
	{ "CROSSBOW_AMMO1_ITEM", ID_CROSSBOW_AMMO1_ITEM },
	/// Pickup Object ID.
	// @mem CROSSBOW_AMMO2_ITEM
	{ "CROSSBOW_AMMO2_ITEM", ID_CROSSBOW_AMMO2_ITEM },
	/// Pickup Object ID.
	// @mem CROSSBOW_AMMO3_ITEM
	{ "CROSSBOW_AMMO3_ITEM", ID_CROSSBOW_AMMO3_ITEM },
	/// Object ID.
	// @mem CROSSBOW_BOLT
	{ "CROSSBOW_BOLT", ID_CROSSBOW_BOLT },
	/// Pickup Object ID.
	// @mem HK_ITEM
	{ "HK_ITEM", ID_HK_ITEM },
	/// Pickup Object ID.
	// @mem HK_AMMO_ITEM
	{ "HK_AMMO_ITEM", ID_HK_AMMO_ITEM },
	/// Pickup Object ID.
	// @mem GRENADE_GUN_ITEM
	{ "GRENADE_GUN_ITEM", ID_GRENADE_GUN_ITEM },
	/// Pickup Object ID.
	// @mem GRENADE_AMMO1_ITEM
	{ "GRENADE_AMMO1_ITEM", ID_GRENADE_AMMO1_ITEM },
	/// Pickup Object ID.
	// @mem GRENADE_AMMO2_ITEM
	{ "GRENADE_AMMO2_ITEM", ID_GRENADE_AMMO2_ITEM },
	/// Pickup Object ID.
	// @mem GRENADE_AMMO3_ITEM
	{ "GRENADE_AMMO3_ITEM", ID_GRENADE_AMMO3_ITEM },
	/// Object ID.
	// @mem GRENADE
	{ "GRENADE", ID_GRENADE },
	/// Pickup Object ID.
	// @mem ROCKET_LAUNCHER_ITEM
	{ "ROCKET_LAUNCHER_ITEM", ID_ROCKET_LAUNCHER_ITEM },
	/// Pickup Object ID.
	// @mem ROCKET_LAUNCHER_AMMO_ITEM
	{ "ROCKET_LAUNCHER_AMMO_ITEM", ID_ROCKET_LAUNCHER_AMMO_ITEM },
	/// Object ID.
	// @mem ROCKET
	{ "ROCKET", ID_ROCKET },
	/// Pickup Object ID.
	// @mem HARPOON_ITEM
	{ "HARPOON_ITEM", ID_HARPOON_ITEM },
	/// Pickup Object ID.
	// @mem HARPOON_AMMO_ITEM
	{ "HARPOON_AMMO_ITEM", ID_HARPOON_AMMO_ITEM },
	/// Object ID.
	// @mem HARPOON
	{ "HARPOON", ID_HARPOON },
	/// Pickup Object ID.
	// @mem GOLDROSE_ITEM
	{ "GOLDROSE_ITEM", ID_GOLDROSE_ITEM },
	/// Pickup Object ID.
	// @mem BIGMEDI_ITEM
	{ "BIGMEDI_ITEM", ID_BIGMEDI_ITEM },
	/// Pickup Object ID.
	// @mem SMALLMEDI_ITEM
	{ "SMALLMEDI_ITEM", ID_SMALLMEDI_ITEM },
	/// Pickup Object ID.
	// @mem LASERSIGHT_ITEM
	{ "LASERSIGHT_ITEM", ID_LASERSIGHT_ITEM },
	/// Pickup Object ID.
	// @mem BINOCULARS_ITEM
	{ "BINOCULARS_ITEM", ID_BINOCULARS_ITEM },
	/// Pickup Object ID.
	// @mem SILENCER_ITEM
	{ "SILENCER_ITEM", ID_SILENCER_ITEM },
	/// Pickup Object ID.
	// @mem FLARE_ITEM
	{ "FLARE_ITEM", ID_FLARE_ITEM },
	/// Pickup Object ID.
	// @mem FLARE_INV_ITEM
	{ "FLARE_INV_ITEM", ID_FLARE_INV_ITEM },
	/// Pickup Object ID.
	// @mem COMPASS_ITEM
	{ "COMPASS_ITEM", ID_COMPASS_ITEM },
	/// Pickup Object ID.
	// @mem DIARY_ITEM
	{ "DIARY_ITEM", ID_DIARY_ITEM },
	/// Pickup Object ID.
	// @mem STOPWATCH_ITEM
	{ "STOPWATCH_ITEM", ID_STOPWATCH_ITEM },
	/// Pickup Object ID.
	// @mem MEMCARD_LOAD_INV_ITEM
	{ "MEMCARD_LOAD_INV_ITEM", ID_MEMCARD_LOAD_INV_ITEM },
	/// Pickup Object ID.
	// @mem MEMCARD_SAVE_INV_ITEM
	{ "MEMCARD_SAVE_INV_ITEM", ID_MEMCARD_SAVE_INV_ITEM },
	/// Pickup Object ID.
	// @mem PC_LOAD_INV_ITEM
	{ "PC_LOAD_INV_ITEM", ID_PC_LOAD_INV_ITEM },
	/// Pickup Object ID.
	// @mem PC_SAVE_INV_ITEM
	{ "PC_SAVE_INV_ITEM", ID_PC_SAVE_INV_ITEM },
	/// Object ID.
	// @mem DIARY_OPEN
	{ "DIARY_OPEN", ID_DIARY_OPEN },
	/// Object ID.
	// @mem INVENTORY_PASSPORT
	{ "INVENTORY_PASSPORT", ID_INVENTORY_PASSPORT },
	/// Object ID.
	// @mem INVENTORY_SUNGLASSES
	{ "INVENTORY_SUNGLASSES", ID_INVENTORY_SUNGLASSES },
	/// Object ID.
	// @mem INVENTORY_KEYS
	{ "INVENTORY_KEYS", ID_INVENTORY_KEYS },
	/// Object ID.
	// @mem INVENTORY_HEADPHONES
	{ "INVENTORY_HEADPHONES", ID_INVENTORY_HEADPHONES },
	/// Object ID.
	// @mem INVENTORY_PHOTO
	{ "INVENTORY_PHOTO", ID_INVENTORY_PHOTO },
	/// Object ID.
	// @mem SMOKE_EMITTER_WHITE
	{ "SMOKE_EMITTER_WHITE", ID_SMOKE_EMITTER_WHITE },
	/// Object ID.
	// @mem SMOKE_EMITTER_BLACK
	{ "SMOKE_EMITTER_BLACK", ID_SMOKE_EMITTER_BLACK },
	/// Object ID.
	// @mem SMOKE_EMITTER
	{ "SMOKE_EMITTER", ID_SMOKE_EMITTER },
	/// Object ID.
	// @mem EARTHQUAKE
	{ "EARTHQUAKE", ID_EARTHQUAKE },
	/// Object ID.
	// @mem BUBBLES
	{ "BUBBLES", ID_BUBBLES },
	/// Object ID.
	// @mem WATERFALLMIST
	{ "WATERFALLMIST", ID_WATERFALLMIST },
	/// Object ID.
	// @mem GUNSHELL
	{ "GUNSHELL", ID_GUNSHELL },
	/// Object ID.
	// @mem SHOTGUNSHELL
	{ "SHOTGUNSHELL", ID_SHOTGUNSHELL },
	/// Object ID.
	// @mem GUN_FLASH
	{ "GUN_FLASH", ID_GUN_FLASH },
	/// Object ID.
	// @mem GUN_FLASH2
	{ "GUN_FLASH2", ID_GUN_FLASH2 },
	/// Object ID.
	// @mem COLOR_LIGHT
	{ "COLOR_LIGHT", ID_COLOR_LIGHT },
	/// Object ID.
	// @mem BLINKING_LIGHT
	{ "BLINKING_LIGHT", ID_BLINKING_LIGHT },
	/// Object ID.
	// @mem PULSE_LIGHT
	{ "PULSE_LIGHT", ID_PULSE_LIGHT },
	/// Object ID.
	// @mem STROBE_LIGHT
	{ "STROBE_LIGHT", ID_STROBE_LIGHT },
	/// Object ID.
	// @mem ELECTRICAL_LIGHT
	{ "ELECTRICAL_LIGHT", ID_ELECTRICAL_LIGHT },
	/// Object ID.
	// @mem LENS_FLARE
	{ "LENS_FLARE", ID_LENS_FLARE },
	/// Object ID.
	// @mem ENERGY_BUBBLES
	{ "ENERGY_BUBBLES", ID_ENERGY_BUBBLES },
	/// Object ID.
	// @mem PLANET_EFFECT
	{ "PLANET_EFFECT", ID_PLANET_EFFECT },
	/// Object ID.
	// @mem BUTTERFLY
	{ "BUTTERFLY", ID_BUTTERFLY },
	/// Object ID.
	// @mem AI_GUARD
	{ "AI_GUARD", ID_AI_GUARD },
	/// Object ID.
	// @mem AI_AMBUSH
	{ "AI_AMBUSH", ID_AI_AMBUSH },
	/// Object ID.
	// @mem AI_PATROL1
	{ "AI_PATROL1", ID_AI_PATROL1 },
	/// Object ID.
	// @mem AI_MODIFY
	{ "AI_MODIFY", ID_AI_MODIFY },
	/// Object ID.
	// @mem AI_FOLLOW
	{ "AI_FOLLOW", ID_AI_FOLLOW },
	/// Object ID.
	// @mem AI_PATROL2
	{ "AI_PATROL2", ID_AI_PATROL2 },
	/// Object ID.
	// @mem AI_X1
	{ "AI_X1", ID_AI_X1 },
	/// Object ID.
	// @mem AI_X2
	{ "AI_X2", ID_AI_X2 },
	/// Object ID.
	// @mem LARA_START_POS
	{ "LARA_START_POS", ID_LARA_START_POS },
	/// Object ID.
	// @mem TELEPORTER
	{ "TELEPORTER", ID_TELEPORTER },
	/// Object ID.
	// @mem LIFT_TELEPORTER
	{ "LIFT_TELEPORTER", ID_LIFT_TELEPORTER },
	/// Object ID.
	// @mem LASER_BARRIER
	{ "LASER_BARRIER", ID_LASER_BARRIER },
	/// Object ID.
	// @mem STEAM_LASERS
	{ "STEAM_LASERS", ID_STEAM_LASERS },
	/// Object ID.
	// @mem FLOOR_LASERS
	{ "FLOOR_LASERS", ID_FLOOR_LASERS },
	/// Object ID.
	// @mem KILL_ALL_TRIGGERS
	{ "KILL_ALL_TRIGGERS", ID_KILL_ALL_TRIGGERS },
	/// Object ID.
	// @mem TRIGGER_TRIGGERER
	{ "TRIGGER_TRIGGERER", ID_TRIGGER_TRIGGERER },
	/// Object ID.
	// @mem HIGH_OBJECT1
	{ "HIGH_OBJECT1", ID_HIGH_OBJECT1 },
	/// Object ID.
	// @mem EMBER_EMITTER
	{ "EMBER_EMITTER", ID_EMBER_EMITTER },
	/// Object ID.
	// @mem SMASH_OBJECT1
	{ "SMASH_OBJECT1", ID_SMASH_OBJECT1 },
	/// Object ID.
	// @mem SMASH_OBJECT2
	{ "SMASH_OBJECT2", ID_SMASH_OBJECT2 },
	/// Object ID.
	// @mem SMASH_OBJECT3
	{ "SMASH_OBJECT3", ID_SMASH_OBJECT3 },
	/// Object ID.
	// @mem SMASH_OBJECT4
	{ "SMASH_OBJECT4", ID_SMASH_OBJECT4 },
	/// Object ID.
	// @mem SMASH_OBJECT5
	{ "SMASH_OBJECT5", ID_SMASH_OBJECT5 },
	/// Object ID.
	// @mem SMASH_OBJECT6
	{ "SMASH_OBJECT6", ID_SMASH_OBJECT6 },
	/// Object ID.
	// @mem SMASH_OBJECT7
	{ "SMASH_OBJECT7", ID_SMASH_OBJECT7 },
	/// Object ID.
	// @mem SMASH_OBJECT8
	{ "SMASH_OBJECT8", ID_SMASH_OBJECT8 },
	/// Object ID.
	// @mem SMASH_OBJECT9
	{ "SMASH_OBJECT9", ID_SMASH_OBJECT9 },
	/// Object ID.
	// @mem SMASH_OBJECT10
	{ "SMASH_OBJECT10", ID_SMASH_OBJECT10 },
	/// Object ID.
	// @mem SMASH_OBJECT11
	{ "SMASH_OBJECT11", ID_SMASH_OBJECT11 },
	/// Object ID.
	// @mem SMASH_OBJECT12
	{ "SMASH_OBJECT12", ID_SMASH_OBJECT12 },
	/// Object ID.
	// @mem SMASH_OBJECT13
	{ "SMASH_OBJECT13", ID_SMASH_OBJECT13 },
	/// Object ID.
	// @mem SMASH_OBJECT14
	{ "SMASH_OBJECT14", ID_SMASH_OBJECT14 },
	/// Object ID.
	// @mem SMASH_OBJECT15
	{ "SMASH_OBJECT15", ID_SMASH_OBJECT15 },
	/// Object ID.
	// @mem SMASH_OBJECT16
	{ "SMASH_OBJECT16", ID_SMASH_OBJECT16 },
	/// Object ID.
	// @mem BODY_PART
	{ "BODY_PART", ID_BODY_PART },
	/// Object ID.
	// @mem CAMERA_TARGET
	{ "CAMERA_TARGET", ID_CAMERA_TARGET },
	/// Object ID.
	// @mem WATERFALL1
	{ "WATERFALL1", ID_WATERFALL1 },
	/// Object ID.
	// @mem WATERFALL2
	{ "WATERFALL2", ID_WATERFALL2 },
	/// Object ID.
	// @mem WATERFALL3
	{ "WATERFALL3", ID_WATERFALL3 },
	/// Object ID.
	// @mem WATERFALL4
	{ "WATERFALL4", ID_WATERFALL4 },
	/// Object ID.
	// @mem WATERFALL5
	{ "WATERFALL5", ID_WATERFALL5 },
	/// Object ID.
	// @mem WATERFALL6
	{ "WATERFALL6", ID_WATERFALL6 },
	/// Object ID.
	// @mem WATERFALLSS1
	{ "WATERFALLSS1", ID_WATERFALLSS1 },
	/// Object ID.
	// @mem WATERFALLSS2
	{ "WATERFALLSS2", ID_WATERFALLSS2 },
	/// Object ID.
	// @mem FISHTANK
	{ "FISHTANK", ID_FISHTANK },
	/// Object ID.
	// @mem DOPPELGANGER_ORIGIN
	{ "DOPPELGANGER_ORIGIN", ID_DOPPELGANGER_ORIGIN },
	/// Object ID.
	// @mem CORPSE
	{ "CORPSE", ID_CORPSE },
	/// Object ID.
	// @mem WRAITH_TRAP
	{ "WRAITH_TRAP", ID_WRAITH_TRAP },
	/// Object ID.
	// @mem WATERFALL_EMITTER
	{ "WATERFALL_EMITTER", ID_WATERFALL_EMITTER },
	/// Object ID.
	// @mem FIREFLY_EMITTER
	{ "FIREFLY_EMITTER", ID_FIREFLY_EMITTER },
	/// Object ID.
	// @mem MESHSWAP1
	{ "MESHSWAP1", ID_MESHSWAP1 },
	/// Object ID.
	// @mem MESHSWAP2
	{ "MESHSWAP2", ID_MESHSWAP2 },
	/// Object ID.
	// @mem MESHSWAP3
	{ "MESHSWAP3", ID_MESHSWAP3 },
	/// Object ID.
	// @mem MESHSWAP4
	{ "MESHSWAP4", ID_MESHSWAP4 },
	/// Object ID.
	// @mem MESHSWAP5
	{ "MESHSWAP5", ID_MESHSWAP5 },
	/// Object ID.
	// @mem MESHSWAP6
	{ "MESHSWAP6", ID_MESHSWAP6 },
	/// Object ID.
	// @mem MESHSWAP7
	{ "MESHSWAP7", ID_MESHSWAP7 },
	/// Object ID.
	// @mem MESHSWAP8
	{ "MESHSWAP8", ID_MESHSWAP8 },
	/// Object ID.
	// @mem MESHSWAP9
	{ "MESHSWAP9", ID_MESHSWAP9 },
	/// Object ID.
	// @mem MESHSWAP10
	{ "MESHSWAP10", ID_MESHSWAP10 },
	/// Object ID.
	// @mem MESHSWAP_BADDY1
	{ "MESHSWAP_BADDY1", ID_MESHSWAP_BADDY1 },
	/// Object ID.
	// @mem MESHSWAP_BADDY2
	{ "MESHSWAP_BADDY2", ID_MESHSWAP_BADDY2 },
	/// Object ID.
	// @mem MESHSWAP_MAFIA2
	{ "MESHSWAP_MAFIA2", ID_MESHSWAP_MAFIA2 },
	/// Object ID.
	// @mem MESHSWAP_IMP
	{ "MESHSWAP_IMP", ID_MESHSWAP_IMP },
	/// Object ID.
	// @mem MESHSWAP_HITMAN
	{ "MESHSWAP_HITMAN", ID_MESHSWAP_HITMAN },
	/// Object ID.
	// @mem MESHSWAP_ROMAN_GOD1
	{ "MESHSWAP_ROMAN_GOD1", ID_MESHSWAP_ROMAN_GOD1 },
	/// Object ID.
	// @mem MESHSWAP_ROMAN_GOD2
	{ "MESHSWAP_ROMAN_GOD2", ID_MESHSWAP_ROMAN_GOD2 },
	/// Object ID.
	// @mem MESHSWAP_MONKEY_MEDIPACK
	{ "MESHSWAP_MONKEY_MEDIPACK", ID_MESHSWAP_MONKEY_MEDIPACK },
	/// Object ID.
	// @mem MESHSWAP_MONKEY_KEY
	{ "MESHSWAP_MONKEY_KEY", ID_MESHSWAP_MONKEY_KEY },
	/// Object ID.
	// @mem MESHSWAP_WINSTON_ARMY_OUTFIT
	{ "MESHSWAP_WINSTON_ARMY_OUTFIT", ID_MESHSWAP_WINSTON_ARMY_OUTFIT },
	/// Object ID.
	// @mem ANIMATING1
	{ "ANIMATING1", ID_ANIMATING1 },
	/// Object ID.
	// @mem ANIMATING2
	{ "ANIMATING2", ID_ANIMATING2 },
	/// Object ID.
	// @mem ANIMATING3
	{ "ANIMATING3", ID_ANIMATING3 },
	/// Object ID.
	// @mem ANIMATING4
	{ "ANIMATING4", ID_ANIMATING4 },
	/// Object ID.
	// @mem ANIMATING5
	{ "ANIMATING5", ID_ANIMATING5 },
	/// Object ID.
	// @mem ANIMATING6
	{ "ANIMATING6", ID_ANIMATING6 },
	/// Object ID.
	// @mem ANIMATING7
	{ "ANIMATING7", ID_ANIMATING7 },
	/// Object ID.
	// @mem ANIMATING8
	{ "ANIMATING8", ID_ANIMATING8 },
	/// Object ID.
	// @mem ANIMATING9
	{ "ANIMATING9", ID_ANIMATING9 },
	/// Object ID.
	// @mem ANIMATING10
	{ "ANIMATING10", ID_ANIMATING10 },
	/// Object ID.
	// @mem ANIMATING11
	{ "ANIMATING11", ID_ANIMATING11 },
	/// Object ID.
	// @mem ANIMATING12
	{ "ANIMATING12", ID_ANIMATING12 },
	/// Object ID.
	// @mem ANIMATING13
	{ "ANIMATING13", ID_ANIMATING13 },
	/// Object ID.
	// @mem ANIMATING14
	{ "ANIMATING14", ID_ANIMATING14 },
	/// Object ID.
	// @mem ANIMATING15
	{ "ANIMATING15", ID_ANIMATING15 },
	/// Object ID.
	// @mem ANIMATING16
	{ "ANIMATING16", ID_ANIMATING16 },
	/// Object ID.
	// @mem ANIMATING17
	{ "ANIMATING17", ID_ANIMATING17 },
	/// Object ID.
	// @mem ANIMATING18
	{ "ANIMATING18", ID_ANIMATING18 },
	/// Object ID.
	// @mem ANIMATING19
	{ "ANIMATING19", ID_ANIMATING19 },
	/// Object ID.
	// @mem ANIMATING20
	{ "ANIMATING20", ID_ANIMATING20 },
	/// Object ID.
	// @mem ANIMATING21
	{ "ANIMATING21", ID_ANIMATING21 },
	/// Object ID.
	// @mem ANIMATING22
	{ "ANIMATING22", ID_ANIMATING22 },
	/// Object ID.
	// @mem ANIMATING23
	{ "ANIMATING23", ID_ANIMATING23 },
	/// Object ID.
	// @mem ANIMATING24
	{ "ANIMATING24", ID_ANIMATING24 },
	/// Object ID.
	// @mem ANIMATING25
	{ "ANIMATING25", ID_ANIMATING25 },
	/// Object ID.
	// @mem ANIMATING26
	{ "ANIMATING26", ID_ANIMATING26 },
	/// Object ID.
	// @mem ANIMATING27
	{ "ANIMATING27", ID_ANIMATING27 },
	/// Object ID.
	// @mem ANIMATING28
	{ "ANIMATING28", ID_ANIMATING28 },
	/// Object ID.
	// @mem ANIMATING29
	{ "ANIMATING29", ID_ANIMATING29 },
	/// Object ID.
	// @mem ANIMATING30
	{ "ANIMATING30", ID_ANIMATING30 },
	/// Object ID.
	// @mem ANIMATING31
	{ "ANIMATING31", ID_ANIMATING31 },
	/// Object ID.
	// @mem ANIMATING32
	{ "ANIMATING32", ID_ANIMATING32 },
	/// Object ID.
	// @mem ANIMATING33
	{ "ANIMATING33", ID_ANIMATING33 },
	/// Object ID.
	// @mem ANIMATING34
	{ "ANIMATING34", ID_ANIMATING34 },
	/// Object ID.
	// @mem ANIMATING35
	{ "ANIMATING35", ID_ANIMATING35 },
	/// Object ID.
	// @mem ANIMATING36
	{ "ANIMATING36", ID_ANIMATING36 },
	/// Object ID.
	// @mem ANIMATING37
	{ "ANIMATING37", ID_ANIMATING37 },
	/// Object ID.
	// @mem ANIMATING38
	{ "ANIMATING38", ID_ANIMATING38 },
	/// Object ID.
	// @mem ANIMATING39
	{ "ANIMATING39", ID_ANIMATING39 },
	/// Object ID.
	// @mem ANIMATING40
	{ "ANIMATING40", ID_ANIMATING40 },
	/// Object ID.
	// @mem ANIMATING41
	{ "ANIMATING41", ID_ANIMATING41 },
	/// Object ID.
	// @mem ANIMATING42
	{ "ANIMATING42", ID_ANIMATING42 },
	/// Object ID.
	// @mem ANIMATING43
	{ "ANIMATING43", ID_ANIMATING43 },
	/// Object ID.
	// @mem ANIMATING44
	{ "ANIMATING44", ID_ANIMATING44 },
	/// Object ID.
	// @mem ANIMATING45
	{ "ANIMATING45", ID_ANIMATING45 },
	/// Object ID.
	// @mem ANIMATING46
	{ "ANIMATING46", ID_ANIMATING46 },
	/// Object ID.
	// @mem ANIMATING47
	{ "ANIMATING47", ID_ANIMATING47 },
	/// Object ID.
	// @mem ANIMATING48
	{ "ANIMATING48", ID_ANIMATING48 },
	/// Object ID.
	// @mem ANIMATING49
	{ "ANIMATING49", ID_ANIMATING49 },
	/// Object ID.
	// @mem ANIMATING50
	{ "ANIMATING50", ID_ANIMATING50 },
	/// Object ID.
	// @mem ANIMATING51
	{ "ANIMATING51", ID_ANIMATING51 },
	/// Object ID.
	// @mem ANIMATING52
	{ "ANIMATING52", ID_ANIMATING52 },
	/// Object ID.
	// @mem ANIMATING53
	{ "ANIMATING53", ID_ANIMATING53 },
	/// Object ID.
	// @mem ANIMATING54
	{ "ANIMATING54", ID_ANIMATING54 },
	/// Object ID.
	// @mem ANIMATING55
	{ "ANIMATING55", ID_ANIMATING55 },
	/// Object ID.
	// @mem ANIMATING56
	{ "ANIMATING56", ID_ANIMATING56 },
	/// Object ID.
	// @mem ANIMATING57
	{ "ANIMATING57", ID_ANIMATING57 },
	/// Object ID.
	// @mem ANIMATING58
	{ "ANIMATING58", ID_ANIMATING58 },
	/// Object ID.
	// @mem ANIMATING59
	{ "ANIMATING59", ID_ANIMATING59 },
	/// Object ID.
	// @mem ANIMATING60
	{ "ANIMATING60", ID_ANIMATING60 },
	/// Object ID.
	// @mem ANIMATING61
	{ "ANIMATING61", ID_ANIMATING61 },
	/// Object ID.
	// @mem ANIMATING62
	{ "ANIMATING62", ID_ANIMATING62 },
	/// Object ID.
	// @mem ANIMATING63
	{ "ANIMATING63", ID_ANIMATING63 },
	/// Object ID.
	// @mem ANIMATING64
	{ "ANIMATING64", ID_ANIMATING64 },
	/// Object ID.
	// @mem ANIMATING65
	{ "ANIMATING65", ID_ANIMATING65 },
	/// Object ID.
	// @mem ANIMATING66
	{ "ANIMATING66", ID_ANIMATING66 },
	/// Object ID.
	// @mem ANIMATING67
	{ "ANIMATING67", ID_ANIMATING67 },
	/// Object ID.
	// @mem ANIMATING68
	{ "ANIMATING68", ID_ANIMATING68 },
	/// Object ID.
	// @mem ANIMATING69
	{ "ANIMATING69", ID_ANIMATING69 },
	/// Object ID.
	// @mem ANIMATING70
	{ "ANIMATING70", ID_ANIMATING70 },
	/// Object ID.
	// @mem ANIMATING71
	{ "ANIMATING71", ID_ANIMATING71 },
	/// Object ID.
	// @mem ANIMATING72
	{ "ANIMATING72", ID_ANIMATING72 },
	/// Object ID.
	// @mem ANIMATING73
	{ "ANIMATING73", ID_ANIMATING73 },
	/// Object ID.
	// @mem ANIMATING74
	{ "ANIMATING74", ID_ANIMATING74 },
	/// Object ID.
	// @mem ANIMATING75
	{ "ANIMATING75", ID_ANIMATING75 },
	/// Object ID.
	// @mem ANIMATING76
	{ "ANIMATING76", ID_ANIMATING76 },
	/// Object ID.
	// @mem ANIMATING77
	{ "ANIMATING77", ID_ANIMATING77 },
	/// Object ID.
	// @mem ANIMATING78
	{ "ANIMATING78", ID_ANIMATING78 },
	/// Object ID.
	// @mem ANIMATING79
	{ "ANIMATING79", ID_ANIMATING79 },
	/// Object ID.
	// @mem ANIMATING80
	{ "ANIMATING80", ID_ANIMATING80 },
	/// Object ID.
	// @mem ANIMATING81
	{ "ANIMATING81", ID_ANIMATING81 },
	/// Object ID.
	// @mem ANIMATING82
	{ "ANIMATING82", ID_ANIMATING82 },
	/// Object ID.
	// @mem ANIMATING83
	{ "ANIMATING83", ID_ANIMATING83 },
	/// Object ID.
	// @mem ANIMATING84
	{ "ANIMATING84", ID_ANIMATING84 },
	/// Object ID.
	// @mem ANIMATING85
	{ "ANIMATING85", ID_ANIMATING85 },
	/// Object ID.
	// @mem ANIMATING86
	{ "ANIMATING86", ID_ANIMATING86 },
	/// Object ID.
	// @mem ANIMATING87
	{ "ANIMATING87", ID_ANIMATING87 },
	/// Object ID.
	// @mem ANIMATING88
	{ "ANIMATING88", ID_ANIMATING88 },
	/// Object ID.
	// @mem ANIMATING89
	{ "ANIMATING89", ID_ANIMATING89 },
	/// Object ID.
	// @mem ANIMATING90
	{ "ANIMATING90", ID_ANIMATING90 },
	/// Object ID.
	// @mem ANIMATING91
	{ "ANIMATING91", ID_ANIMATING91 },
	/// Object ID.
	// @mem ANIMATING92
	{ "ANIMATING92", ID_ANIMATING92 },
	/// Object ID.
	// @mem ANIMATING93
	{ "ANIMATING93", ID_ANIMATING93 },
	/// Object ID.
	// @mem ANIMATING94
	{ "ANIMATING94", ID_ANIMATING94 },
	/// Object ID.
	// @mem ANIMATING95
	{ "ANIMATING95", ID_ANIMATING95 },
	/// Object ID.
	// @mem ANIMATING96
	{ "ANIMATING96", ID_ANIMATING96 },
	/// Object ID.
	// @mem ANIMATING97
	{ "ANIMATING97", ID_ANIMATING97 },
	/// Object ID.
	// @mem ANIMATING98
	{ "ANIMATING98", ID_ANIMATING98 },
	/// Object ID.
	// @mem ANIMATING99
	{ "ANIMATING99", ID_ANIMATING99 },
	/// Object ID.
	// @mem ANIMATING100
	{ "ANIMATING100", ID_ANIMATING100 },
	/// Object ID.
	// @mem ANIMATING101
	{ "ANIMATING101", ID_ANIMATING101 },
	/// Object ID.
	// @mem ANIMATING102
	{ "ANIMATING102", ID_ANIMATING102 },
	/// Object ID.
	// @mem ANIMATING103
	{ "ANIMATING103", ID_ANIMATING103 },
	/// Object ID.
	// @mem ANIMATING104
	{ "ANIMATING104", ID_ANIMATING104 },
	/// Object ID.
	// @mem ANIMATING105
	{ "ANIMATING105", ID_ANIMATING105 },
	/// Object ID.
	// @mem ANIMATING106
	{ "ANIMATING106", ID_ANIMATING106 },
	/// Object ID.
	// @mem ANIMATING107
	{ "ANIMATING107", ID_ANIMATING107 },
	/// Object ID.
	// @mem ANIMATING108
	{ "ANIMATING108", ID_ANIMATING108 },
	/// Object ID.
	// @mem ANIMATING109
	{ "ANIMATING109", ID_ANIMATING109 },
	/// Object ID.
	// @mem ANIMATING110
	{ "ANIMATING110", ID_ANIMATING110 },
	/// Object ID.
	// @mem ANIMATING111
	{ "ANIMATING111", ID_ANIMATING111 },
	/// Object ID.
	// @mem ANIMATING112
	{ "ANIMATING112", ID_ANIMATING112 },
	/// Object ID.
	// @mem ANIMATING113
	{ "ANIMATING113", ID_ANIMATING113 },
	/// Object ID.
	// @mem ANIMATING114
	{ "ANIMATING114", ID_ANIMATING114 },
	/// Object ID.
	// @mem ANIMATING115
	{ "ANIMATING115", ID_ANIMATING115 },
	/// Object ID.
	// @mem ANIMATING116
	{ "ANIMATING116", ID_ANIMATING116 },
	/// Object ID.
	// @mem ANIMATING117
	{ "ANIMATING117", ID_ANIMATING117 },
	/// Object ID.
	// @mem ANIMATING118
	{ "ANIMATING118", ID_ANIMATING118 },
	/// Object ID.
	// @mem ANIMATING119
	{ "ANIMATING119", ID_ANIMATING119 },
	/// Object ID.
	// @mem ANIMATING120
	{ "ANIMATING120", ID_ANIMATING120 },
	/// Object ID.
	// @mem ANIMATING121
	{ "ANIMATING121", ID_ANIMATING121 },
	/// Object ID.
	// @mem ANIMATING122
	{ "ANIMATING122", ID_ANIMATING122 },
	/// Object ID.
	// @mem ANIMATING123
	{ "ANIMATING123", ID_ANIMATING123 },
	/// Object ID.
	// @mem ANIMATING124
	{ "ANIMATING124", ID_ANIMATING124 },
	/// Object ID.
	// @mem ANIMATING125
	{ "ANIMATING125", ID_ANIMATING125 },
	/// Object ID.
	// @mem ANIMATING126
	{ "ANIMATING126", ID_ANIMATING126 },
	/// Object ID.
	// @mem ANIMATING127
	{ "ANIMATING127", ID_ANIMATING127 },
	/// Object ID.
	// @mem ANIMATING128
	{ "ANIMATING128", ID_ANIMATING128 },
	/// Object ID.
	// @mem LASERHEAD_BASE
	{ "LASERHEAD_BASE", ID_LASERHEAD_BASE },
	/// Object ID.
	// @mem LASERHEAD_TENTACLE
	{ "LASERHEAD_TENTACLE", ID_LASERHEAD_TENTACLE },
	/// Object ID.
	// @mem BRIDGE_FLAT
	{ "BRIDGE_FLAT", ID_BRIDGE_FLAT },
	/// Object ID.
	// @mem BRIDGE_TILT1
	{ "BRIDGE_TILT1", ID_BRIDGE_TILT1 },
	/// Object ID.
	// @mem BRIDGE_TILT2
	{ "BRIDGE_TILT2", ID_BRIDGE_TILT2 },
	/// Object ID.
	// @mem BRIDGE_TILT3
	{ "BRIDGE_TILT3", ID_BRIDGE_TILT3 },
	/// Object ID.
	// @mem BRIDGE_TILT4
	{ "BRIDGE_TILT4", ID_BRIDGE_TILT4 },
	/// Object ID.
	// @mem BRIDGE_CUSTOM
	{ "BRIDGE_CUSTOM", ID_BRIDGE_CUSTOM },
	/// Object ID.
	// @mem HORIZON
	{ "HORIZON", ID_HORIZON },
	/// Sprite Object ID.
	// @mem SKY_GRAPHICS
	{ "SKY_GRAPHICS", ID_SKY_GRAPHICS },
	/// Sprite Object ID.
	// @mem DEFAULT_SPRITES
	{ "DEFAULT_SPRITES", ID_DEFAULT_SPRITES },
	/// Sprite Object ID.
	// @mem MISC_SPRITES
	{ "MISC_SPRITES", ID_MISC_SPRITES },
	/// Sprite Object ID.
	// @mem CUSTOM_SPRITES
	{ "CUSTOM_SPRITES", ID_CUSTOM_SPRITES },
	/// Sprite Object ID.
	// @mem FIRE_SPRITES
	{ "FIRE_SPRITES", ID_FIRE_SPRITES },
	/// Sprite Object ID.
	// @mem SMOKE_SPRITES
	{ "SMOKE_SPRITES", ID_SMOKE_SPRITES },
	/// Sprite Object ID.
	// @mem SPARK_SPRITE
	{ "SPARK_SPRITE", ID_SPARK_SPRITE },
	/// Sprite Object ID.
	// @mem DRIP_SPRITE
	{ "DRIP_SPRITE", ID_DRIP_SPRITE },
	/// Sprite Object ID.
	// @mem EXPLOSION_SPRITES
	{ "EXPLOSION_SPRITES", ID_EXPLOSION_SPRITES },
	/// Sprite Object ID.
	// @mem MOTORBOAT_FOAM_SPRITES
	{ "MOTORBOAT_FOAM_SPRITES", ID_MOTORBOAT_FOAM_SPRITES },
	/// Sprite Object ID.
	// @mem RUBBER_BOAT_WAVE_SPRITES
	{ "RUBBER_BOAT_WAVE_SPRITES", ID_RUBBER_BOAT_WAVE_SPRITES },
	/// Sprite Object ID.
	// @mem SKIDOO_SNOW_TRAIL_SPRITES
	{ "SKIDOO_SNOW_TRAIL_SPRITES", ID_SKIDOO_SNOW_TRAIL_SPRITES },
	/// Sprite Object ID.
	// @mem KAYAK_PADDLE_TRAIL_SPRITE
	{ "KAYAK_PADDLE_TRAIL_SPRITE", ID_KAYAK_PADDLE_TRAIL_SPRITE },
	/// Object ID.
	// @mem KAYAK_WAKE_SPRTIES
	{ "KAYAK_WAKE_SPRTIES", ID_KAYAK_WAKE_SPRTIES },
	/// Object ID.
	// @mem BINOCULAR_GRAPHICS
	{ "BINOCULAR_GRAPHICS", ID_BINOCULAR_GRAPHICS },
	/// Sprite Object ID.
	// @mem LASERSIGHT_GRAPHICS
	{ "LASERSIGHT_GRAPHICS", ID_LASERSIGHT_GRAPHICS },
	/// Sprite Object ID.
	// @mem CAUSTIC_TEXTURES
	{ "CAUSTIC_TEXTURES", ID_CAUSTIC_TEXTURES },
	/// Sprite Object ID.
	// @mem BAR_BORDER_GRAPHICS
	{ "BAR_BORDER_GRAPHICS", ID_BAR_BORDER_GRAPHICS },
	/// Sprite Object ID.
	// @mem HEALTH_BAR_TEXTURE
	{ "HEALTH_BAR_TEXTURE", ID_HEALTH_BAR_TEXTURE },
	/// Sprite Object ID.
	// @mem AIR_BAR_TEXTURE
	{ "AIR_BAR_TEXTURE", ID_AIR_BAR_TEXTURE },
	/// Sprite Object ID.
	// @mem DASH_BAR_TEXTURE
	{ "DASH_BAR_TEXTURE", ID_DASH_BAR_TEXTURE },
	/// Sprite Object ID.
	// @mem SFX_BAR_TEXTURE
	{ "SFX_BAR_TEXTURE", ID_SFX_BAR_TEXTURE },
	/// Sprite Object ID.
	// @mem WATERFALL_SPRITES
	{ "WATERFALL_SPRITES", ID_WATERFALL_SPRITES },
	/// Sprite Object ID.
	// @mem FIREFLY_SPRITES
	{ "FIREFLY_SPRITES", ID_FIREFLY_SPRITES },
	/// Sprite Object ID.
	// @mem CROSSHAIR_GRAPHICS
	{ "CROSSHAIR_GRAPHICS", ID_CROSSHAIR_GRAPHICS },
	/// Sprite Object ID.
	// @mem SPEEDOMETER_GRAPHICS
	{ "SPEEDOMETER_GRAPHICS", ID_SPEEDOMETER_GRAPHICS },
	/// Sprite Object ID.
	// @mem CUSTOM_BAR_GRAPHICS
	{ "CUSTOM_BAR_GRAPHICS", ID_CUSTOM_BAR_GRAPHICS },
	/// Sprite Object ID.
	// @mem CUSTOM_AMMO_GRAPHICS
	{ "CUSTOM_AMMO_GRAPHICS", ID_CUSTOM_AMMO_GRAPHICS },
	/// Sprite Object ID.
	// @mem DIARY_SPRITES
	{ "DIARY_SPRITES", ID_DIARY_SPRITES },
	/// Sprite Object ID.
	// @mem DIARY_ENTRY_SPRITES
	{ "DIARY_ENTRY_SPRITES", ID_DIARY_ENTRY_SPRITES },
	/// Sprite Object ID.
	// @mem SNOW_SPRITES
	{ "SNOW_SPRITES", ID_SNOW_SPRITES },
	/// Sprite Object ID.
	// @mem RAIN_SPRITES
	{ "RAIN_SPRITES", ID_RAIN_SPRITES }
};
