local NO_JOINT_BITS = 0
local STRING_LOAD_GAME = "load_game"
local INV_ROT_Y = 1

local COL = {
    ITEM_ID = 1,
    YOFFSET = 2,
    SCALE = 3,
    ROTATION = 4,
    FLAGS = 5,
    DISPLAY_NAME = 6,
    JOINT = 7,
    ORIENTATION = 8
}

local function GetInventoryData(row)
    return {
        itemID = row[COL.ITEM_ID],
        yOffset = row[COL.YOFFSET],
        scale = row[COL.SCALE],
        rotation = row[COL.ROTATION],
        flags = row[COL.FLAGS],
        name = row[COL.DISPLAY_NAME],
        joint = row[COL.JOINT],
        orientation = row[COL.ORIENTATION],
    }
end

local pickupConstants = {
	-- Weapons
	{ TEN.Objects.ObjID.PISTOLS_ITEM, 6, 0.5, Rotation(244.0, 90.0, 276.0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_PISTOLS, "pistols", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.UZI_ITEM, -4, 0.5, Rotation(135.0, -90.0, 90.0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_UZI, "uzis" , NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.SHOTGUN_ITEM, -6, 0.8, Rotation(270.0, -20.0, 45), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_SHOTGUN, "shotgun", 0x01, INV_ROT_Y },
	{ TEN.Objects.ObjID.REVOLVER_ITEM, 0, 0.5, Rotation(60.0, -90.0, 85.0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_REVOLVER, "revolver" , 0x01, INV_ROT_Y },
	--{ TEN.Objects.ObjID.REVOLVER_ITEM, 0, 0.5, Rotation(60.0, 90.0, 85.0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_REVOLVER, "revolver_lasersight", 0x0B, INV_ROT_Y },
	{ TEN.Objects.ObjID.CROSSBOW_ITEM, 0, 0.5, Rotation(33.0, -90.0, 0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_CROSSBOW, "crossbow", 0x01, INV_ROT_Y },
	--{ TEN.Objects.ObjID.CROSSBOW_ITEM, 0, 0.5, Rotation(33.0, -90.0, 0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_CROSSBOW, "crossbow_lasersight", 0x03, INV_ROT_Y },
	{ TEN.Objects.ObjID.HK_ITEM, 0, 0.5, Rotation(280.0, 0, 0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_HK, "hk", 0x01, INV_ROT_Y },
	--{ TEN.Objects.ObjID.HK_ITEM, 0, 0.5, Rotation(280.0, -45.0, 0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_HK, "hk_lasersight", NO_JOINT_BITS, INV_ROT_Y },
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_rapid_mode", NO_JOINT_BITS, INV_ROT_Y },
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_burst_mode", NO_JOINT_BITS, INV_ROT_Y },
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_sniper_mode", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.GRENADE_GUN_ITEM, 0, 0.5, Rotation(0, 90.0, 65), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_GRENADEGUN, "grenade_launcher", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.HARPOON_ITEM, 0, 0.5, Rotation(-65.0, 0, -20.0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_HARPOON, "harpoon_gun", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.ROCKET_LAUNCHER_ITEM, 0, 0.5, Rotation(80.0, 180.0, 0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_ROCKET, "rocket_launcher", NO_JOINT_BITS, INV_ROT_Y },

	-- { TEN.Objects.ObjID.PISTOLS_AMMO_ITEM, 4, 0.5, Rotation(0, 0, 0), ItemAction.USE, "pistol_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.UZI_AMMO_ITEM, 5, 0.5, Rotation(29.5, 0, 0), ItemAction.USE, "uzi_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.SHOTGUN_AMMO1_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "shotgun_normal_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.SHOTGUN_AMMO2_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "shotgun_wideshot_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.REVOLVER_AMMO_ITEM, 0, 0.5, Rotation(-16.0, 180.0, 0), ItemAction.USE, "revolver_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.CROSSBOW_AMMO1_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_normal_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.CROSSBOW_AMMO2_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_poison_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.CROSSBOW_AMMO3_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_explosive_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.GRENADE_AMMO1_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_normal_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.GRENADE_AMMO2_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_super_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.GRENADE_AMMO3_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_flash_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.HARPOON_AMMO_ITEM, 3, 0.5, Rotation(15.0, 0, 0), ItemAction.USE, "harpoon_gun_ammo", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.ROCKET_LAUNCHER_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 15.0), ItemAction.USE, "rocket_launcher_ammo", NO_JOINT_BITS, INV_ROT_Y },

	-- Miscellaneous
	{ TEN.Objects.ObjID.LASERSIGHT_ITEM, 2, 0.5, Rotation(10.0, 90.0, 0), ItemAction.USE | ItemAction.COMBINE, "lasersight", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.SILENCER_ITEM, 1, 0.5, Rotation(10.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "silencer", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.BIGMEDI_ITEM, 2, 0.7, Rotation(0, 180.0, 0), ItemAction.USE, "large_medipack", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.SMALLMEDI_ITEM, 0, 0.7, Rotation(112.0, 180.0, 0), ItemAction.USE, "small_medipack", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.BINOCULARS_ITEM, -1, 0.5, Rotation(10.0, 180.0, 0), ItemAction.USE, "binoculars", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.FLARE_INV_ITEM, 52, 0.8, Rotation(0, 0, 0), ItemAction.USE, "flares", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.STOPWATCH_ITEM, 2, 0.8, Rotation(0, 0, 0), STATISTICS, "statistics", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.PC_LOAD_INV_ITEM, 52, 0.3, Rotation(0, 180.0, 0), ItemAction.LOAD, "load_game", NO_JOINT_BITS, INV_ROT_Y },
	-- { TEN.Objects.ObjID.PC_SAVE_INV_ITEM, 52, 0.3, Rotation(0, 180.0, 0), ItemAction.SAVE, "save_game", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.BURNING_TORCH_ITEM, 14, 0.5, Rotation(90.0, 0, 0), ItemAction.USE, "torch", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.CROWBAR_ITEM, 4, 0.5, Rotation(90.0, 0, 0), ItemAction.USE, "crowbar", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.DIARY_ITEM, 0, 0.3, Rotation(0, 180.0, 0), ItemAction.USE, "diary", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.COMPASS_ITEM, -14, 0.5, Rotation(90.0, 180.0, 0), 0, "load_game", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, "mechanical_scarab", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, "mechanical_scarab_1", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, "mechanical_scarab_2", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN1_EMPTY, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_empty", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN1_1, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_1l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN1_2, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_2l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN1_3, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_3l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_EMPTY, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_empty", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_1, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_1l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_2, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_2l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_3, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_3l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_4, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_4l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.WATERSKIN2_5, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_5l", NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.DIARY_OPEN, 0, 0.9, Rotation(0, 90.0, 0), ItemAction.USE, "load_game", NO_JOINT_BITS, INV_ROT_Y},

	-- Puzzles
	{ TEN.Objects.ObjID.PUZZLE_ITEM1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Puzzle combos
	{ TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO2, 18, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Keys
	{ TEN.Objects.ObjID.KEY_ITEM1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Key combos
	{ TEN.Objects.ObjID.KEY_ITEM1_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM1_COMBO2, 18, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM2_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM2_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM3_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM3_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM4_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM4_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM5_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM5_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM6_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM6_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM7_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM7_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM8_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM8_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM9_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM9_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM10_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM10_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM11_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM11_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM12_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM12_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM13_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM13_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM14_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM14_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM15_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM15_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM16_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.KEY_ITEM16_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Pickups
	{ TEN.Objects.ObjID.PICKUP_ITEM1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Pickup combos
	{ TEN.Objects.ObjID.PICKUP_ITEM1_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM1_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM2_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM2_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM3_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM3_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM4_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM4_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM5_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM5_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM6_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM6_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM7_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM7_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM8_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM8_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM9_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM9_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM10_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM10_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM11_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM11_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM12_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM12_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM13_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM13_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM14_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM14_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM15_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM15_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM16_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.PICKUP_ITEM16_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Examines
	{ TEN.Objects.ObjID.EXAMINE1, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE2, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE3, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE4, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE5, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE6, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE7, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE8, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },

	-- Examines combos
	{ TEN.Objects.ObjID.EXAMINE1_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE1_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE2_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE2_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE3_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE3_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE4_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE4_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE5_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE5_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE6_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE6_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE7_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE7_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE8_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
	{ TEN.Objects.ObjID.EXAMINE8_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE | ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y },
}

local function lookupValue(lookupValue, returnColName)
    local lookupCol = COL.ITEM_ID
    local returnCol = COL[returnColName]
    if not returnCol then
        error("Invalid column name")
    end

    for _, row in ipairs(pickupConstants) do
        if row[lookupCol] == lookupValue then
            return row[returnCol]
        end
    end
	print("Not Found")
    return nil -- Not found
end

return {constants = pickupConstants, GetInventoryData = GetInventoryData, GetItemData = lookupValue}
-- local combineTable =
-- {
-- 	{ CombineRevolverLasersight, TEN.Objects.ObjID.REVOLVER_ITEM, TEN.Objects.ObjID.LASERSIGHT, TEN.Objects.ObjID.REVOLVER_LASER },
-- 	{ CombineCrossbowLasersight, TEN.Objects.ObjID.CROSSBOW, TEN.Objects.ObjID.LASERSIGHT, TEN.Objects.ObjID.CROSSBOW_LASER },
-- 	{ CombineHKLasersight, TEN.Objects.ObjID.HK, TEN.Objects.ObjID.LASERSIGHT, TEN.Objects.ObjID.HK_LASERSIGHT },
-- 	{ CombinePuzzleItem1, TEN.Objects.ObjID.PUZZLE1_COMBO1, TEN.Objects.ObjID.PUZZLE1_COMBO2, TEN.Objects.ObjID.PUZZLE1 },
-- 	{ CombinePuzzleItem2, TEN.Objects.ObjID.PUZZLE2_COMBO1, TEN.Objects.ObjID.PUZZLE2_COMBO2, TEN.Objects.ObjID.PUZZLE2 },
-- 	{ CombinePuzzleItem3, TEN.Objects.ObjID.PUZZLE3_COMBO1, TEN.Objects.ObjID.PUZZLE3_COMBO2, TEN.Objects.ObjID.PUZZLE3 },
-- 	{ CombinePuzzleItem4, TEN.Objects.ObjID.PUZZLE4_COMBO1, TEN.Objects.ObjID.PUZZLE4_COMBO2, TEN.Objects.ObjID.PUZZLE4 },
-- 	{ CombinePuzzleItem5, TEN.Objects.ObjID.PUZZLE5_COMBO1, TEN.Objects.ObjID.PUZZLE5_COMBO2, TEN.Objects.ObjID.PUZZLE5 },
-- 	{ CombinePuzzleItem6, TEN.Objects.ObjID.PUZZLE6_COMBO1, TEN.Objects.ObjID.PUZZLE6_COMBO2, TEN.Objects.ObjID.PUZZLE6 },
-- 	{ CombinePuzzleItem7, TEN.Objects.ObjID.PUZZLE7_COMBO1, TEN.Objects.ObjID.PUZZLE7_COMBO2, TEN.Objects.ObjID.PUZZLE7 },
-- 	{ CombinePuzzleItem8, TEN.Objects.ObjID.PUZZLE8_COMBO1, TEN.Objects.ObjID.PUZZLE8_COMBO2, TEN.Objects.ObjID.PUZZLE8 },
-- 	{ CombinePuzzleItem9, TEN.Objects.ObjID.PUZZLE9_COMBO1, TEN.Objects.ObjID.PUZZLE9_COMBO2, TEN.Objects.ObjID.PUZZLE9 },
-- 	{ CombinePuzzleItem10, TEN.Objects.ObjID.PUZZLE10_COMBO1, TEN.Objects.ObjID.PUZZLE10_COMBO2, TEN.Objects.ObjID.PUZZLE10 },
-- 	{ CombinePuzzleItem11, TEN.Objects.ObjID.PUZZLE11_COMBO1, TEN.Objects.ObjID.PUZZLE11_COMBO2, TEN.Objects.ObjID.PUZZLE11 },
-- 	{ CombinePuzzleItem12, TEN.Objects.ObjID.PUZZLE12_COMBO1, TEN.Objects.ObjID.PUZZLE12_COMBO2, TEN.Objects.ObjID.PUZZLE12 },
-- 	{ CombinePuzzleItem13, TEN.Objects.ObjID.PUZZLE13_COMBO1, TEN.Objects.ObjID.PUZZLE13_COMBO2, TEN.Objects.ObjID.PUZZLE13 },
-- 	{ CombinePuzzleItem14, TEN.Objects.ObjID.PUZZLE14_COMBO1, TEN.Objects.ObjID.PUZZLE14_COMBO2, TEN.Objects.ObjID.PUZZLE14 },
-- 	{ CombinePuzzleItem15, TEN.Objects.ObjID.PUZZLE15_COMBO1, TEN.Objects.ObjID.PUZZLE15_COMBO2, TEN.Objects.ObjID.PUZZLE15 },
-- 	{ CombinePuzzleItem16, TEN.Objects.ObjID.PUZZLE16_COMBO1, TEN.Objects.ObjID.PUZZLE16_COMBO2, TEN.Objects.ObjID.PUZZLE16 },
-- 	{ CombineKeyItem1, TEN.Objects.ObjID.KEY1_COMBO1, TEN.Objects.ObjID.KEY1_COMBO2, TEN.Objects.ObjID.KEY1 },
-- 	{ CombineKeyItem2, TEN.Objects.ObjID.KEY2_COMBO1, TEN.Objects.ObjID.KEY2_COMBO2, TEN.Objects.ObjID.KEY2 },
-- 	{ CombineKeyItem3, TEN.Objects.ObjID.KEY3_COMBO1, TEN.Objects.ObjID.KEY3_COMBO2, TEN.Objects.ObjID.KEY3 },
-- 	{ CombineKeyItem4, TEN.Objects.ObjID.KEY4_COMBO1, TEN.Objects.ObjID.KEY4_COMBO2, TEN.Objects.ObjID.KEY4 },
-- 	{ CombineKeyItem5, TEN.Objects.ObjID.KEY5_COMBO1, TEN.Objects.ObjID.KEY5_COMBO2, TEN.Objects.ObjID.KEY5 },
-- 	{ CombineKeyItem6, TEN.Objects.ObjID.KEY6_COMBO1, TEN.Objects.ObjID.KEY6_COMBO2, TEN.Objects.ObjID.KEY6 },
-- 	{ CombineKeyItem7, TEN.Objects.ObjID.KEY7_COMBO1, TEN.Objects.ObjID.KEY7_COMBO2, TEN.Objects.ObjID.KEY7 },
-- 	{ CombineKeyItem8, TEN.Objects.ObjID.KEY8_COMBO1, TEN.Objects.ObjID.KEY8_COMBO2, TEN.Objects.ObjID.KEY8 },
-- 	{ CombineKeyItem9, TEN.Objects.ObjID.KEY9_COMBO1, TEN.Objects.ObjID.KEY9_COMBO2, TEN.Objects.ObjID.KEY9 },
-- 	{ CombineKeyItem10, TEN.Objects.ObjID.KEY10_COMBO1, TEN.Objects.ObjID.KEY10_COMBO2, TEN.Objects.ObjID.KEY10 },
-- 	{ CombineKeyItem11, TEN.Objects.ObjID.KEY11_COMBO1, TEN.Objects.ObjID.KEY11_COMBO2, TEN.Objects.ObjID.KEY11 },
-- 	{ CombineKeyItem12, TEN.Objects.ObjID.KEY12_COMBO1, TEN.Objects.ObjID.KEY12_COMBO2, TEN.Objects.ObjID.KEY12 },
-- 	{ CombineKeyItem13, TEN.Objects.ObjID.KEY13_COMBO1, TEN.Objects.ObjID.KEY13_COMBO2, TEN.Objects.ObjID.KEY13 },
-- 	{ CombineKeyItem14, TEN.Objects.ObjID.KEY14_COMBO1, TEN.Objects.ObjID.KEY14_COMBO2, TEN.Objects.ObjID.KEY14 },
-- 	{ CombineKeyItem15, TEN.Objects.ObjID.KEY15_COMBO1, TEN.Objects.ObjID.KEY15_COMBO2, TEN.Objects.ObjID.KEY15 },
-- 	{ CombineKeyItem16, TEN.Objects.ObjID.KEY16_COMBO1, TEN.Objects.ObjID.KEY16_COMBO2, TEN.Objects.ObjID.KEY16 },
-- 	{ CombinePickupItem1, TEN.Objects.ObjID.PICKUP1_COMBO1, TEN.Objects.ObjID.PICKUP1_COMBO2, TEN.Objects.ObjID.PICKUP1 },
-- 	{ CombinePickupItem2, TEN.Objects.ObjID.PICKUP2_COMBO1, TEN.Objects.ObjID.PICKUP2_COMBO2, TEN.Objects.ObjID.PICKUP2 },
-- 	{ CombinePickupItem3, TEN.Objects.ObjID.PICKUP3_COMBO1, TEN.Objects.ObjID.PICKUP3_COMBO2, TEN.Objects.ObjID.PICKUP3 },
-- 	{ CombinePickupItem4, TEN.Objects.ObjID.PICKUP4_COMBO1, TEN.Objects.ObjID.PICKUP4_COMBO2, TEN.Objects.ObjID.PICKUP4 },
-- 	{ CombinePickupItem5, TEN.Objects.ObjID.PICKUP5_COMBO1, TEN.Objects.ObjID.PICKUP5_COMBO2, TEN.Objects.ObjID.PICKUP5 },
-- 	{ CombinePickupItem6, TEN.Objects.ObjID.PICKUP6_COMBO1, TEN.Objects.ObjID.PICKUP6_COMBO2, TEN.Objects.ObjID.PICKUP6 },
-- 	{ CombinePickupItem7, TEN.Objects.ObjID.PICKUP7_COMBO1, TEN.Objects.ObjID.PICKUP7_COMBO2, TEN.Objects.ObjID.PICKUP7 },
-- 	{ CombinePickupItem8, TEN.Objects.ObjID.PICKUP8_COMBO1, TEN.Objects.ObjID.PICKUP8_COMBO2, TEN.Objects.ObjID.PICKUP8 },
-- 	{ CombinePickupItem9, TEN.Objects.ObjID.PICKUP9_COMBO1, TEN.Objects.ObjID.PICKUP9_COMBO2, TEN.Objects.ObjID.PICKUP9 },
-- 	{ CombinePickupItem10, TEN.Objects.ObjID.PICKUP10_COMBO1, TEN.Objects.ObjID.PICKUP10_COMBO2, TEN.Objects.ObjID.PICKUP10 },
-- 	{ CombinePickupItem11, TEN.Objects.ObjID.PICKUP11_COMBO1, TEN.Objects.ObjID.PICKUP11_COMBO2, TEN.Objects.ObjID.PICKUP11 },
-- 	{ CombinePickupItem12, TEN.Objects.ObjID.PICKUP12_COMBO1, TEN.Objects.ObjID.PICKUP12_COMBO2, TEN.Objects.ObjID.PICKUP12 },
-- 	{ CombinePickupItem13, TEN.Objects.ObjID.PICKUP13_COMBO1, TEN.Objects.ObjID.PICKUP13_COMBO2, TEN.Objects.ObjID.PICKUP13 },
-- 	{ CombinePickupItem14, TEN.Objects.ObjID.PICKUP14_COMBO1, TEN.Objects.ObjID.PICKUP14_COMBO2, TEN.Objects.ObjID.PICKUP14 },
-- 	{ CombinePickupItem15, TEN.Objects.ObjID.PICKUP15_COMBO1, TEN.Objects.ObjID.PICKUP15_COMBO2, TEN.Objects.ObjID.PICKUP15 },
-- 	{ CombinePickupItem16, TEN.Objects.ObjID.PICKUP16_COMBO1, TEN.Objects.ObjID.PICKUP16_COMBO2, TEN.Objects.ObjID.PICKUP16 },
-- 	{ CombineExamine1, TEN.Objects.ObjID.EXAMINE1_COMBO1, TEN.Objects.ObjID.EXAMINE1_COMBO2, TEN.Objects.ObjID.EXAMINE1 },
-- 	{ CombineExamine2, TEN.Objects.ObjID.EXAMINE2_COMBO1, TEN.Objects.ObjID.EXAMINE2_COMBO2, TEN.Objects.ObjID.EXAMINE2 },
-- 	{ CombineExamine3, TEN.Objects.ObjID.EXAMINE3_COMBO1, TEN.Objects.ObjID.EXAMINE3_COMBO2, TEN.Objects.ObjID.EXAMINE3 },
-- 	{ CombineExamine4, TEN.Objects.ObjID.EXAMINE4_COMBO1, TEN.Objects.ObjID.EXAMINE4_COMBO2, TEN.Objects.ObjID.EXAMINE4 },
-- 	{ CombineExamine5, TEN.Objects.ObjID.EXAMINE5_COMBO1, TEN.Objects.ObjID.EXAMINE5_COMBO2, TEN.Objects.ObjID.EXAMINE5 },
-- 	{ CombineExamine6, TEN.Objects.ObjID.EXAMINE6_COMBO1, TEN.Objects.ObjID.EXAMINE6_COMBO2, TEN.Objects.ObjID.EXAMINE6 },
-- 	{ CombineExamine7, TEN.Objects.ObjID.EXAMINE7_COMBO1, TEN.Objects.ObjID.EXAMINE7_COMBO2, TEN.Objects.ObjID.EXAMINE7 },
-- 	{ CombineExamine8, TEN.Objects.ObjID.EXAMINE8_COMBO1, TEN.Objects.ObjID.EXAMINE8_COMBO2, TEN.Objects.ObjID.EXAMINE8 },
-- 	{ CombineClockWorkBeetle, TEN.Objects.ObjID.BEETLE_PART1, TEN.Objects.ObjID.BEETLE_PART2, TEN.Objects.ObjID.BEETLE }
-- }